# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# pylint: disable=wrong-import-position

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ._patch import *  # pylint: disable=unused-wildcard-import


from ._models_py3 import (  # type: ignore
    AppServiceCertificate,
    AppServiceCertificateCollection,
    AppServiceCertificateOrder,
    AppServiceCertificateOrderCollection,
    AppServiceCertificateOrderPatchResource,
    AppServiceCertificatePatchResource,
    AppServiceCertificateResource,
    CertificateDetails,
    CertificateEmail,
    CertificateOrderAction,
    CertificateOrderContact,
    CsmOperationCollection,
    CsmOperationDescription,
    CsmOperationDescriptionProperties,
    CsmOperationDisplay,
    DataProviderMetadata,
    DataTableResponseColumn,
    DataTableResponseObject,
    DefaultErrorResponse,
    DefaultErrorResponseError,
    DefaultErrorResponseErrorDetailsItem,
    DetectorInfo,
    DetectorResponse,
    DetectorResponseCollection,
    DiagnosticData,
    Dimension,
    KeyValuePairStringObject,
    LogSpecification,
    MetricAvailability,
    MetricSpecification,
    NameIdentifier,
    ProxyOnlyResource,
    ProxyResource,
    QueryUtterancesResult,
    QueryUtterancesResults,
    ReissueCertificateOrderRequest,
    Rendering,
    RenewCertificateOrderRequest,
    Resource,
    SampleUtterance,
    ServiceSpecification,
    SiteSeal,
    SiteSealRequest,
    Status,
    SupportTopic,
    SystemData,
    TrackedResource,
)

from ._certificate_registration_mgmt_client_enums import (  # type: ignore
    CertificateOrderActionType,
    CertificateOrderStatus,
    CertificateProductType,
    CreatedByType,
    DetectorType,
    InsightStatus,
    KeyVaultSecretStatus,
    ProvisioningState,
    RenderingType,
    ResourceNotRenewableReason,
)
from ._patch import __all__ as _patch_all
from ._patch import *
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "AppServiceCertificate",
    "AppServiceCertificateCollection",
    "AppServiceCertificateOrder",
    "AppServiceCertificateOrderCollection",
    "AppServiceCertificateOrderPatchResource",
    "AppServiceCertificatePatchResource",
    "AppServiceCertificateResource",
    "CertificateDetails",
    "CertificateEmail",
    "CertificateOrderAction",
    "CertificateOrderContact",
    "CsmOperationCollection",
    "CsmOperationDescription",
    "CsmOperationDescriptionProperties",
    "CsmOperationDisplay",
    "DataProviderMetadata",
    "DataTableResponseColumn",
    "DataTableResponseObject",
    "DefaultErrorResponse",
    "DefaultErrorResponseError",
    "DefaultErrorResponseErrorDetailsItem",
    "DetectorInfo",
    "DetectorResponse",
    "DetectorResponseCollection",
    "DiagnosticData",
    "Dimension",
    "KeyValuePairStringObject",
    "LogSpecification",
    "MetricAvailability",
    "MetricSpecification",
    "NameIdentifier",
    "ProxyOnlyResource",
    "ProxyResource",
    "QueryUtterancesResult",
    "QueryUtterancesResults",
    "ReissueCertificateOrderRequest",
    "Rendering",
    "RenewCertificateOrderRequest",
    "Resource",
    "SampleUtterance",
    "ServiceSpecification",
    "SiteSeal",
    "SiteSealRequest",
    "Status",
    "SupportTopic",
    "SystemData",
    "TrackedResource",
    "CertificateOrderActionType",
    "CertificateOrderStatus",
    "CertificateProductType",
    "CreatedByType",
    "DetectorType",
    "InsightStatus",
    "KeyVaultSecretStatus",
    "ProvisioningState",
    "RenderingType",
    "ResourceNotRenewableReason",
]
__all__.extend([p for p in _patch_all if p not in __all__])  # pyright: ignore
_patch_sdk()
