# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
import pytest
from azure.mgmt.subscription import SubscriptionClient

from devtools_testutils import AzureMgmtRecordedTestCase, RandomNameResourceGroupPreparer, recorded_by_proxy

AZURE_LOCATION = "eastus"


@pytest.mark.skip("you may need to update the auto-generated test case before run it")
class TestSubscriptionSubscriptionOperations(AzureMgmtRecordedTestCase):
    def setup_method(self, method):
        self.client = self.create_mgmt_client(SubscriptionClient)

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy
    def test_subscription_accept_ownership_status(self, resource_group):
        response = self.client.subscription.accept_ownership_status(
            subscription_id="str",
            api_version="2025-11-01-preview",
        )

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy
    def test_subscription_begin_accept_ownership(self, resource_group):
        response = self.client.subscription.begin_accept_ownership(
            subscription_id="str",
            requestbody_body={"properties": {"displayName": "str", "managementGroupId": "str", "tags": {"str": "str"}}},
            api_version="2025-11-01-preview",
        ).result()  # call '.result()' to poll until service return final result

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy
    def test_subscription_cancel(self, resource_group):
        response = self.client.subscription.cancel(
            api_version="2025-11-01-preview",
        )

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy
    def test_subscription_enable(self, resource_group):
        response = self.client.subscription.enable(
            api_version="2025-11-01-preview",
        )

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy
    def test_subscription_rename(self, resource_group):
        response = self.client.subscription.rename(
            body={"subscriptionName": "str"},
            api_version="2025-11-01-preview",
        )

        # please add some check logic here by yourself
        # ...
