# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
import pytest
from azure.mgmt.previewalertrule import PreviewAlertRuleMgmtClient

from devtools_testutils import AzureMgmtRecordedTestCase, RandomNameResourceGroupPreparer, recorded_by_proxy

AZURE_LOCATION = "eastus"


@pytest.mark.skip("you may need to update the auto-generated test case before run it")
class TestPreviewAlertRuleMgmt(AzureMgmtRecordedTestCase):
    def setup_method(self, method):
        self.client = self.create_mgmt_client(PreviewAlertRuleMgmtClient)

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy
    def test_preview_alert_rule(self, resource_group):
        response = self.client.preview_alert_rule(
            resource_id="str",
            parameters={
                "location": "str",
                "properties": {
                    "timespan": "1 day, 0:00:00",
                    "scheduledQueryRuleProperties": {
                        "location": "str",
                        "properties": {
                            "criteria": {
                                "allOf": [
                                    {
                                        "alertSensitivity": "str",
                                        "criterionType": "str",
                                        "dimensions": [{"name": "str", "operator": "str", "values": ["str"]}],
                                        "failingPeriods": {
                                            "minFailingPeriodsToAlert": 0,
                                            "numberOfEvaluationPeriods": 0,
                                        },
                                        "ignoreDataBefore": "2020-02-20 00:00:00",
                                        "metricMeasureColumn": "str",
                                        "metricName": "str",
                                        "operator": "str",
                                        "query": "str",
                                        "resourceIdColumn": "str",
                                        "threshold": 0.0,
                                        "timeAggregation": "str",
                                    }
                                ]
                            },
                            "description": "str",
                            "displayName": "str",
                            "enabled": bool,
                            "evaluationFrequency": "1 day, 0:00:00",
                            "overrideQueryTimeRange": "1 day, 0:00:00",
                            "scopes": ["str"],
                            "severity": 0.0,
                            "targetResourceTypes": ["str"],
                            "windowSize": "1 day, 0:00:00",
                        },
                        "kind": "str",
                        "tags": {"str": "str"},
                    },
                },
            },
        )

        # please add some check logic here by yourself
        # ...
