# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class ActionType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Extensible enum. Indicates the action type. "Internal" refers to actions that are for internal
    only APIs.
    """

    INTERNAL = "Internal"
    """Actions are for internal-only APIs."""


class AppliedScopeType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type of the Applied Scope."""

    SINGLE = "Single"
    SHARED = "Shared"
    MANAGEMENT_GROUP = "ManagementGroup"


class ApplyDiscountOn(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The customer action on which the discount is applied. Supported values are Purchase, Consume,
    and Renew. Validation: Required, one of supported values.
    """

    PURCHASE = "Purchase"
    CONSUME = "Consume"
    RENEW = "Renew"


class BenefitType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Represents benefit model type for validation."""

    SAVINGS_PLAN = "SavingsPlan"
    MACC = "MACC"
    CONDITIONAL_CREDITS = "ConditionalCredits"
    CREDITS = "Credits"


class BillingPlan(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Represents the billing plan in ISO 8601 format. Required only for monthly billing plans."""

    P1_M = "P1M"


class CommitmentGrain(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Grain."""

    HOURLY = "Hourly"
    FULL_TERM = "FullTerm"
    UNKNOWN = "Unknown"


class ConditionalCreditEntityType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type of conditional credit entity."""

    PRIMARY = "Primary"
    CONTRIBUTOR = "Contributor"


class ConditionalCreditsProvisioningState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The provisioning state of the resource."""

    UNKNOWN = "Unknown"
    SUCCEEDED = "Succeeded"
    FAILED = "Failed"
    CANCELED = "Canceled"
    PENDING = "Pending"


class ConditionalCreditStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The status of the conditional credit."""

    UNKNOWN = "Unknown"
    SCHEDULED = "Scheduled"
    ACTIVE = "Active"
    PENDING = "Pending"
    FAILED = "Failed"
    CANCELED = "Canceled"
    COMPLETED = "Completed"
    STOPPED = "Stopped"
    PENDING_SETTLEMENT = "PendingSettlement"


class CreatedByType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The kind of entity that created the resource."""

    USER = "User"
    """The entity was created by a user."""
    APPLICATION = "Application"
    """The entity was created by an application."""
    MANAGED_IDENTITY = "ManagedIdentity"
    """The entity was created by a managed identity."""
    KEY = "Key"
    """The entity was created by a key."""


class CreditExpirationPolicy(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Expiration policy of the Credit."""

    NONE = "None"
    """No policy applied to the expiration of this credit"""
    SUSPEND_BILLING_PROFILE = "SuspendBillingProfile"
    """Billing profile is suspended when the credit expires"""


class CreditRedemptionPolicy(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Redemption policy of the Credit."""

    NOT_APPLICABLE = "NotApplicable"
    """Redemption policy is not applicable for this credit"""
    AUTO_REDEEM = "AutoRedeem"
    """Credit is automatically redeemed"""
    MANUAL_REDEEM = "ManualRedeem"
    """Credit is manually redeemed"""


class CreditStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Status of the credit."""

    UNKNOWN = "Unknown"
    """Credit status is unknown"""
    PENDING = "Pending"
    """Credit is pending activation"""
    ACTIVE = "Active"
    """Credit is active and available for use"""
    SUCCEEDED = "Succeeded"
    """Credit operation succeeded"""
    CANCELED = "Canceled"
    """Credit has been cancelled"""
    FAILED = "Failed"
    """Credit operation failed"""
    EXPIRED = "Expired"
    """Credit has expired"""
    EXHAUSTED = "Exhausted"
    """Credit has been fully consumed"""
    NOT_STARTED = "NotStarted"
    """Credit application has not started yet"""


class DiscountAppliedScopeType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """List of applied scopes supported for discounts."""

    BILLING_ACCOUNT = "BillingAccount"
    BILLING_PROFILE = "BillingProfile"
    CUSTOMER = "Customer"


class DiscountCombinationRule(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The discount combination rule when there are multiple applicable custom prices. Validation:
    Required. Supported values are Stackable and BestOf.
    """

    BEST_OF = "BestOf"
    STACKABLE = "Stackable"


class DiscountEntityType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """This defines whether the entity being created is primary or affiliate. Supported values:
    primary, affiliate. Validation: Required, must match one of the 2 values.
    """

    PRIMARY = "Primary"
    AFFILIATE = "Affiliate"


class DiscountProvisioningState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Provisioning states of Discount."""

    UNKNOWN = "Unknown"
    PENDING = "Pending"
    SUCCEEDED = "Succeeded"
    CANCELED = "Canceled"
    FAILED = "Failed"


class DiscountRuleType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The type of the priceable node pricing rule. Validation: Required. Supported values are
    fixedPriceLock, fixedListPrice, and priceCeiling.
    """

    FIXED_PRICE_LOCK = "FixedPriceLock"
    FIXED_LIST_PRICE = "FixedListPrice"
    PRICE_CEILING = "PriceCeiling"


class DiscountStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Represents the current status of the discount."""

    ACTIVE = "Active"
    PENDING = "Pending"
    FAILED = "Failed"
    CANCELED = "Canceled"
    EXPIRED = "Expired"


class DiscountType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Defines the type of discount. Supported values are ProductFamily, Product, Sku, CustomPrice,
    and CustomPriceMultiCurrency.
    """

    PRODUCT_FAMILY = "ProductFamily"
    PRODUCT = "Product"
    SKU = "Sku"
    CUSTOM_PRICE = "CustomPrice"
    CUSTOM_PRICE_MULTI_CURRENCY = "CustomPriceMultiCurrency"


class EnablementMode(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Represents the enablement status of a feature or settings."""

    UNKNOWN = "Unknown"
    ENABLED = "Enabled"
    DISABLED = "Disabled"


class InstanceFlexibility(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Turning this on will apply the reservation discount to other VMs in the same VM size group."""

    ON = "On"
    OFF = "Off"


class MaccEntityType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Represents type of the object being operated on. Possible values are primary or contributor."""

    PRIMARY = "Primary"
    CONTRIBUTOR = "Contributor"


class MaccMilestoneStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Represents the current status of the Milestone."""

    UNKNOWN = "Unknown"
    SCHEDULED = "Scheduled"
    ACTIVE = "Active"
    PENDING = "Pending"
    FAILED = "Failed"
    COMPLETED = "Completed"
    CANCELED = "Canceled"
    REMOVED = "Removed"
    PENDING_SETTLEMENT = "PendingSettlement"
    SHORTFALL_CHARGED = "ShortfallCharged"
    SHORTFALL_WAIVED = "ShortfallWaived"


class MaccStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Represents the current status of the MACC."""

    UNKNOWN = "Unknown"
    SCHEDULED = "Scheduled"
    ACTIVE = "Active"
    PENDING = "Pending"
    FAILED = "Failed"
    CANCELED = "Canceled"
    COMPLETED = "Completed"
    STOPPED = "Stopped"
    PENDING_SETTLEMENT = "PendingSettlement"
    SHORTFALL_CHARGED = "ShortfallCharged"
    SHORTFALL_WAIVED = "ShortfallWaived"


class ManagedServiceIdentityType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type of managed service identity (where both SystemAssigned and UserAssigned types are
    allowed).
    """

    NONE = "None"
    SYSTEM_ASSIGNED = "SystemAssigned"
    USER_ASSIGNED = "UserAssigned"
    SYSTEM_ASSIGNED_USER_ASSIGNED = "SystemAssigned,UserAssigned"


class ManagedServiceIdentityType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type of managed service identity (where both SystemAssigned and UserAssigned types are
    allowed).
    """

    NONE = "None"
    """No managed identity."""
    SYSTEM_ASSIGNED = "SystemAssigned"
    """System assigned managed identity."""
    USER_ASSIGNED = "UserAssigned"
    """User assigned managed identity."""
    SYSTEM_ASSIGNED_USER_ASSIGNED = "SystemAssigned,UserAssigned"
    """System and user assigned managed identity."""


class MilestoneStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Current status of the milestone."""

    UNKNOWN = "Unknown"
    SCHEDULED = "Scheduled"
    ACTIVE = "Active"
    PENDING = "Pending"
    FAILED = "Failed"
    COMPLETED = "Completed"
    CANCELED = "Canceled"
    REMOVED = "Removed"
    PENDING_SETTLEMENT = "PendingSettlement"
    MISSED = "Missed"


class Origin(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The intended executor of the operation; as in Resource Based Access Control (RBAC) and audit
    logs UX. Default value is "user,system".
    """

    USER = "user"
    """Indicates the operation is initiated by a user."""
    SYSTEM = "system"
    """Indicates the operation is initiated by a system."""
    USER_SYSTEM = "user,system"
    """Indicates the operation is initiated by a user or system."""


class PaymentStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Describes whether the payment is completed, failed, cancelled or scheduled in the future."""

    SUCCEEDED = "Succeeded"
    FAILED = "Failed"
    SCHEDULED = "Scheduled"
    CANCELLED = "Cancelled"


class PricingPolicy(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Supported values: Protected, Locked."""

    PROTECTED = "Protected"
    LOCKED = "Locked"


class ProvisioningState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Provisioning state."""

    CREATING = "Creating"
    PENDING_BILLING = "PendingBilling"
    CONFIRMED_BILLING = "ConfirmedBilling"
    CREATED = "Created"
    SUCCEEDED = "Succeeded"
    CANCELLED = "Cancelled"
    EXPIRED = "Expired"
    FAILED = "Failed"


class ReservedResourceType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The type of the resource that is being reserved."""

    VIRTUAL_MACHINES = "VirtualMachines"
    SQL_DATABASES = "SqlDatabases"
    SUSE_LINUX = "SuseLinux"
    COSMOS_DB = "CosmosDb"
    RED_HAT = "RedHat"
    SQL_DATA_WAREHOUSE = "SqlDataWarehouse"
    V_MWARE_CLOUD_SIMPLE = "VMwareCloudSimple"
    RED_HAT_OSA = "RedHatOsa"
    DATABRICKS = "Databricks"
    APP_SERVICE = "AppService"
    MANAGED_DISK = "ManagedDisk"
    BLOCK_BLOB = "BlockBlob"
    REDIS_CACHE = "RedisCache"
    AZURE_DATA_EXPLORER = "AzureDataExplorer"
    MY_SQL = "MySql"
    MARIA_DB = "MariaDb"
    POSTGRE_SQL = "PostgreSql"
    DEDICATED_HOST = "DedicatedHost"
    SAP_HANA = "SapHana"
    SQL_AZURE_HYBRID_BENEFIT = "SqlAzureHybridBenefit"
    AVS = "AVS"
    DATA_FACTORY = "DataFactory"
    NET_APP_STORAGE = "NetAppStorage"
    AZURE_FILES = "AzureFiles"
    SQL_EDGE = "SqlEdge"
    VIRTUAL_MACHINE_SOFTWARE = "VirtualMachineSoftware"


class SkuTier(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """This field is required to be implemented by the Resource Provider if the service has more than
    one tier, but is not required on a PUT.
    """

    FREE = "Free"
    """The Free service tier."""
    BASIC = "Basic"
    """The Basic service tier."""
    STANDARD = "Standard"
    """The Standard service tier."""
    PREMIUM = "Premium"
    """The Premium service tier."""


class Term(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Represent benefit term in ISO 8601 format."""

    P1_Y = "P1Y"
    P3_Y = "P3Y"
    P5_Y = "P5Y"
