# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
import pytest
from azure.mgmt.tenantactivitylogalerts.aio import TenantActivityLogAlertsMgmtClient

from devtools_testutils import AzureMgmtRecordedTestCase, RandomNameResourceGroupPreparer
from devtools_testutils.aio import recorded_by_proxy_async

AZURE_LOCATION = "eastus"


@pytest.mark.skip("you may need to update the auto-generated test case before run it")
class TestTenantActivityLogAlertsMgmtTenantActivityLogAlertsOperationsAsync(AzureMgmtRecordedTestCase):
    def setup_method(self, method):
        self.client = self.create_mgmt_client(TenantActivityLogAlertsMgmtClient, is_async=True)

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy_async
    async def test_tenant_activity_log_alerts_list_by_tenant(self, resource_group):
        response = self.client.tenant_activity_log_alerts.list_by_tenant()
        result = [r async for r in response]
        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy_async
    async def test_tenant_activity_log_alerts_get(self, resource_group):
        response = await self.client.tenant_activity_log_alerts.get(
            management_group_name="str",
            alert_rule_name="str",
        )

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy_async
    async def test_tenant_activity_log_alerts_create_or_update(self, resource_group):
        response = await self.client.tenant_activity_log_alerts.create_or_update(
            management_group_name="str",
            alert_rule_name="str",
            tenant_activity_log_alert_rule={
                "properties": {
                    "actions": {
                        "actionGroups": [
                            {
                                "actionGroupId": "str",
                                "actionProperties": {"str": "str"},
                                "webhookProperties": {"str": "str"},
                            }
                        ]
                    },
                    "condition": {
                        "allOf": [
                            {
                                "anyOf": [{"containsAny": ["str"], "equals": "str", "field": "str"}],
                                "containsAny": ["str"],
                                "equals": "str",
                                "field": "str",
                            }
                        ]
                    },
                    "description": "str",
                    "enabled": bool,
                    "scopes": ["str"],
                    "tenantScope": "str",
                },
                "id": "str",
                "location": "str",
                "name": "str",
                "systemData": {
                    "createdAt": "2020-02-20 00:00:00",
                    "createdBy": "str",
                    "createdByType": "str",
                    "lastModifiedAt": "2020-02-20 00:00:00",
                    "lastModifiedBy": "str",
                    "lastModifiedByType": "str",
                },
                "tags": {"str": "str"},
                "type": "str",
            },
        )

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy_async
    async def test_tenant_activity_log_alerts_update(self, resource_group):
        response = await self.client.tenant_activity_log_alerts.update(
            management_group_name="str",
            alert_rule_name="str",
            tenant_activity_log_alert_rule_patch={"properties": {"enabled": bool}, "tags": {"str": "str"}},
        )

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy_async
    async def test_tenant_activity_log_alerts_delete(self, resource_group):
        response = await self.client.tenant_activity_log_alerts.delete(
            management_group_name="str",
            alert_rule_name="str",
        )

        # please add some check logic here by yourself
        # ...

    @RandomNameResourceGroupPreparer(location=AZURE_LOCATION)
    @recorded_by_proxy_async
    async def test_tenant_activity_log_alerts_list_by_management_group(self, resource_group):
        response = self.client.tenant_activity_log_alerts.list_by_management_group(
            management_group_name="str",
        )
        result = [r async for r in response]
        # please add some check logic here by yourself
        # ...
