# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class ActionType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Action that should be applied."""

    ADD_ACTION_GROUPS = "AddActionGroups"
    """AddActionGroups"""
    REMOVE_ALL_ACTION_GROUPS = "RemoveAllActionGroups"
    """RemoveAllActionGroups"""


class CreatedByType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The type of identity that created the resource."""

    USER = "User"
    APPLICATION = "Application"
    MANAGED_IDENTITY = "ManagedIdentity"
    KEY = "Key"


class DaysOfWeek(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Days of week."""

    SUNDAY = "Sunday"
    """Sunday"""
    MONDAY = "Monday"
    """Monday"""
    TUESDAY = "Tuesday"
    """Tuesday"""
    WEDNESDAY = "Wednesday"
    """Wednesday"""
    THURSDAY = "Thursday"
    """Thursday"""
    FRIDAY = "Friday"
    """Friday"""
    SATURDAY = "Saturday"
    """Saturday"""


class Field(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Field for a given condition."""

    SEVERITY = "Severity"
    """Severity"""
    MONITOR_SERVICE = "MonitorService"
    """MonitorService"""
    MONITOR_CONDITION = "MonitorCondition"
    """MonitorCondition"""
    SIGNAL_TYPE = "SignalType"
    """SignalType"""
    TARGET_RESOURCE_TYPE = "TargetResourceType"
    """TargetResourceType"""
    TARGET_RESOURCE = "TargetResource"
    """TargetResource"""
    TARGET_RESOURCE_GROUP = "TargetResourceGroup"
    """TargetResourceGroup"""
    ALERT_RULE_ID = "AlertRuleId"
    """AlertRuleId"""
    ALERT_RULE_NAME = "AlertRuleName"
    """AlertRuleName"""
    DESCRIPTION = "Description"
    """Description"""
    ALERT_CONTEXT = "AlertContext"
    """AlertContext"""


class Operator(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Operator for a given condition."""

    EQUALS = "Equals"
    """Equals"""
    NOT_EQUALS = "NotEquals"
    """NotEquals"""
    CONTAINS = "Contains"
    """Contains"""
    DOES_NOT_CONTAIN = "DoesNotContain"
    """DoesNotContain"""


class RecurrenceType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies when the recurrence should be applied."""

    DAILY = "Daily"
    """Daily"""
    WEEKLY = "Weekly"
    """Weekly"""
    MONTHLY = "Monthly"
    """Monthly"""
