# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from copy import deepcopy
from typing import Any, Awaitable, Optional, TYPE_CHECKING, cast
from typing_extensions import Self

from azure.core.pipeline import policies
from azure.core.rest import AsyncHttpResponse, HttpRequest
from azure.core.settings import settings
from azure.mgmt.core import AsyncARMPipelineClient
from azure.mgmt.core.policies import AsyncARMAutoResourceProviderRegistrationPolicy
from azure.mgmt.core.tools import get_arm_endpoints

from .. import models as _models
from .._utils.serialization import Deserializer, Serializer
from ._configuration import HybridNetworkManagementClientConfiguration
from .operations import (
    ArtifactManifestsOperations,
    ArtifactStoresOperations,
    ComponentsOperations,
    ConfigurationGroupSchemasOperations,
    ConfigurationGroupValuesOperations,
    NetworkFunctionDefinitionGroupsOperations,
    NetworkFunctionDefinitionVersionsOperations,
    NetworkFunctionsOperations,
    NetworkServiceDesignGroupsOperations,
    NetworkServiceDesignVersionsOperations,
    Operations,
    ProxyArtifactOperations,
    PublishersOperations,
    SiteNetworkServicesOperations,
    SitesOperations,
)

if TYPE_CHECKING:
    from azure.core import AzureClouds
    from azure.core.credentials_async import AsyncTokenCredential


class HybridNetworkManagementClient:  # pylint: disable=too-many-instance-attributes
    """The resources in this swagger specification will be used to manage the hybrid network site
    network service.

    :ivar operations: Operations operations
    :vartype operations: Microsoft.HybridNetwork.aio.operations.Operations
    :ivar site_network_services: SiteNetworkServicesOperations operations
    :vartype site_network_services:
     Microsoft.HybridNetwork.aio.operations.SiteNetworkServicesOperations
    :ivar configuration_group_values: ConfigurationGroupValuesOperations operations
    :vartype configuration_group_values:
     Microsoft.HybridNetwork.aio.operations.ConfigurationGroupValuesOperations
    :ivar network_functions: NetworkFunctionsOperations operations
    :vartype network_functions: Microsoft.HybridNetwork.aio.operations.NetworkFunctionsOperations
    :ivar publishers: PublishersOperations operations
    :vartype publishers: Microsoft.HybridNetwork.aio.operations.PublishersOperations
    :ivar sites: SitesOperations operations
    :vartype sites: Microsoft.HybridNetwork.aio.operations.SitesOperations
    :ivar components: ComponentsOperations operations
    :vartype components: Microsoft.HybridNetwork.aio.operations.ComponentsOperations
    :ivar artifact_stores: ArtifactStoresOperations operations
    :vartype artifact_stores: Microsoft.HybridNetwork.aio.operations.ArtifactStoresOperations
    :ivar artifact_manifests: ArtifactManifestsOperations operations
    :vartype artifact_manifests: Microsoft.HybridNetwork.aio.operations.ArtifactManifestsOperations
    :ivar proxy_artifact: ProxyArtifactOperations operations
    :vartype proxy_artifact: Microsoft.HybridNetwork.aio.operations.ProxyArtifactOperations
    :ivar configuration_group_schemas: ConfigurationGroupSchemasOperations operations
    :vartype configuration_group_schemas:
     Microsoft.HybridNetwork.aio.operations.ConfigurationGroupSchemasOperations
    :ivar network_function_definition_groups: NetworkFunctionDefinitionGroupsOperations operations
    :vartype network_function_definition_groups:
     Microsoft.HybridNetwork.aio.operations.NetworkFunctionDefinitionGroupsOperations
    :ivar network_function_definition_versions: NetworkFunctionDefinitionVersionsOperations
     operations
    :vartype network_function_definition_versions:
     Microsoft.HybridNetwork.aio.operations.NetworkFunctionDefinitionVersionsOperations
    :ivar network_service_design_groups: NetworkServiceDesignGroupsOperations operations
    :vartype network_service_design_groups:
     Microsoft.HybridNetwork.aio.operations.NetworkServiceDesignGroupsOperations
    :ivar network_service_design_versions: NetworkServiceDesignVersionsOperations operations
    :vartype network_service_design_versions:
     Microsoft.HybridNetwork.aio.operations.NetworkServiceDesignVersionsOperations
    :param credential: Credential needed for the client to connect to Azure. Required.
    :type credential: ~azure.core.credentials_async.AsyncTokenCredential
    :param subscription_id: The ID of the target subscription. Required.
    :type subscription_id: str
    :param base_url: Service URL. Default value is None.
    :type base_url: str
    :keyword cloud_setting: The cloud setting for which to get the ARM endpoint. Default value is
     None.
    :paramtype cloud_setting: ~azure.core.AzureClouds
    :keyword api_version: Api Version. Default value is "2025-03-30". Note that overriding this
     default value may result in unsupported behavior.
    :paramtype api_version: str
    :keyword int polling_interval: Default waiting time between two polls for LRO operations if no
     Retry-After header is present.
    """

    def __init__(
        self,
        credential: "AsyncTokenCredential",
        subscription_id: str,
        base_url: Optional[str] = None,
        *,
        cloud_setting: Optional["AzureClouds"] = None,
        **kwargs: Any
    ) -> None:
        _cloud = cloud_setting or settings.current.azure_cloud  # type: ignore
        _endpoints = get_arm_endpoints(_cloud)
        if not base_url:
            base_url = _endpoints["resource_manager"]
        credential_scopes = kwargs.pop("credential_scopes", _endpoints["credential_scopes"])
        self._config = HybridNetworkManagementClientConfiguration(
            credential=credential,
            subscription_id=subscription_id,
            cloud_setting=cloud_setting,
            credential_scopes=credential_scopes,
            **kwargs
        )

        _policies = kwargs.pop("policies", None)
        if _policies is None:
            _policies = [
                policies.RequestIdPolicy(**kwargs),
                self._config.headers_policy,
                self._config.user_agent_policy,
                self._config.proxy_policy,
                policies.ContentDecodePolicy(**kwargs),
                AsyncARMAutoResourceProviderRegistrationPolicy(),
                self._config.redirect_policy,
                self._config.retry_policy,
                self._config.authentication_policy,
                self._config.custom_hook_policy,
                self._config.logging_policy,
                policies.DistributedTracingPolicy(**kwargs),
                policies.SensitiveHeaderCleanupPolicy(**kwargs) if self._config.redirect_policy else None,
                self._config.http_logging_policy,
            ]
        self._client: AsyncARMPipelineClient = AsyncARMPipelineClient(
            base_url=cast(str, base_url), policies=_policies, **kwargs
        )

        client_models = {k: v for k, v in _models.__dict__.items() if isinstance(v, type)}
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)
        self._serialize.client_side_validation = False
        self.operations = Operations(self._client, self._config, self._serialize, self._deserialize)
        self.site_network_services = SiteNetworkServicesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.configuration_group_values = ConfigurationGroupValuesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.network_functions = NetworkFunctionsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.publishers = PublishersOperations(self._client, self._config, self._serialize, self._deserialize)
        self.sites = SitesOperations(self._client, self._config, self._serialize, self._deserialize)
        self.components = ComponentsOperations(self._client, self._config, self._serialize, self._deserialize)
        self.artifact_stores = ArtifactStoresOperations(self._client, self._config, self._serialize, self._deserialize)
        self.artifact_manifests = ArtifactManifestsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.proxy_artifact = ProxyArtifactOperations(self._client, self._config, self._serialize, self._deserialize)
        self.configuration_group_schemas = ConfigurationGroupSchemasOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.network_function_definition_groups = NetworkFunctionDefinitionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.network_function_definition_versions = NetworkFunctionDefinitionVersionsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.network_service_design_groups = NetworkServiceDesignGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.network_service_design_versions = NetworkServiceDesignVersionsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )

    def _send_request(
        self, request: HttpRequest, *, stream: bool = False, **kwargs: Any
    ) -> Awaitable[AsyncHttpResponse]:
        """Runs the network request through the client's chained policies.

        >>> from azure.core.rest import HttpRequest
        >>> request = HttpRequest("GET", "https://www.example.org/")
        <HttpRequest [GET], url: 'https://www.example.org/'>
        >>> response = await client._send_request(request)
        <AsyncHttpResponse: 200 OK>

        For more information on this code flow, see https://aka.ms/azsdk/dpcodegen/python/send_request

        :param request: The network request you want to make. Required.
        :type request: ~azure.core.rest.HttpRequest
        :keyword bool stream: Whether the response payload will be streamed. Defaults to False.
        :return: The response of your network call. Does not do error handling on your response.
        :rtype: ~azure.core.rest.AsyncHttpResponse
        """

        request_copy = deepcopy(request)
        request_copy.url = self._client.format_url(request_copy.url)
        return self._client.send_request(request_copy, stream=stream, **kwargs)  # type: ignore

    async def close(self) -> None:
        await self._client.close()

    async def __aenter__(self) -> Self:
        await self._client.__aenter__()
        return self

    async def __aexit__(self, *exc_details: Any) -> None:
        await self._client.__aexit__(*exc_details)
