# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class AlertSeverity(int, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Severity of the alert. Should be an integer between [0-4]. Value of 0 is severest. Relevant and
    required only for rules of the kind LogAlert.
    """

    ENUM_0 = 0
    """0"""
    ENUM_1 = 1
    """1"""
    ENUM_2 = 2
    """2"""
    ENUM_3 = 3
    """3"""
    ENUM_4 = 4
    """4"""


class AlertState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The state of the alert after the evaluation."""

    NO_ALERT = "NoAlert"
    """NoAlert"""
    FIRED = "Fired"
    """Fired"""
    FIRING = "Firing"
    """Firing"""
    RESOLVING = "Resolving"
    """Resolving"""
    RESOLVED = "Resolved"
    """Resolved"""


class ConditionOperator(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The criteria operator. Relevant and required only for rules of the kind LogAlert."""

    EQUALS = "Equals"
    """Equals"""
    GREATER_THAN = "GreaterThan"
    """GreaterThan"""
    GREATER_THAN_OR_EQUAL = "GreaterThanOrEqual"
    """GreaterThanOrEqual"""
    LESS_THAN = "LessThan"
    """LessThan"""
    LESS_THAN_OR_EQUAL = "LessThanOrEqual"
    """LessThanOrEqual"""
    GREATER_OR_LESS_THAN = "GreaterOrLessThan"
    """GreaterOrLessThan"""


class CriterionType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Specifies the type of threshold criteria."""

    STATIC_THRESHOLD_CRITERION = "StaticThresholdCriterion"
    """StaticThresholdCriterion"""
    DYNAMIC_THRESHOLD_CRITERION = "DynamicThresholdCriterion"
    """DynamicThresholdCriterion"""


class DimensionOperator(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Operator for dimension values."""

    INCLUDE = "Include"
    """Include"""
    EXCLUDE = "Exclude"
    """Exclude"""


class Kind(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Indicates the type of scheduled query rule. The default is LogAlert."""

    LOG_ALERT = "LogAlert"
    """LogAlert"""
    EVENT_LOG_ALERT = "EventLogAlert"
    """EventLogAlert"""
    LOG_TO_METRIC = "LogToMetric"
    """LogToMetric"""


class TimeAggregation(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Aggregation type. Relevant and required only for rules of the kind LogAlert."""

    COUNT = "Count"
    """Count"""
    AVERAGE = "Average"
    """Average"""
    MINIMUM = "Minimum"
    """Minimum"""
    MAXIMUM = "Maximum"
    """Maximum"""
    TOTAL = "Total"
    """Total"""
