# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# pylint: disable=useless-super-delegation

import datetime
from typing import Any, Mapping, Optional, TYPE_CHECKING, Union, overload

from .._utils.model_base import Model as _Model, rest_field

if TYPE_CHECKING:
    from .. import models as _models


class DimensionNameAndValue(_Model):
    """Dimension name and value.

    :ivar name: Name of the dimension. Required.
    :vartype name: str
    :ivar value: Value of the dimension. Required.
    :vartype value: str
    """

    name: str = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Name of the dimension. Required."""
    value: str = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Value of the dimension. Required."""

    @overload
    def __init__(
        self,
        *,
        name: str,
        value: str,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class ErrorAdditionalInfo(_Model):
    """The resource management error additional info.

    :ivar type: The additional info type.
    :vartype type: str
    :ivar info: The additional info.
    :vartype info: any
    """

    type: Optional[str] = rest_field(visibility=["read"])
    """The additional info type."""
    info: Optional[Any] = rest_field(visibility=["read"])
    """The additional info."""


class ErrorDetail(_Model):
    """The error detail.

    :ivar code: The error code.
    :vartype code: str
    :ivar message: The error message.
    :vartype message: str
    :ivar target: The error target.
    :vartype target: str
    :ivar details: The error details.
    :vartype details: list[~azure.mgmt.previewalertrule.models.ErrorDetail]
    :ivar additional_info: The error additional info.
    :vartype additional_info: list[~azure.mgmt.previewalertrule.models.ErrorAdditionalInfo]
    """

    code: Optional[str] = rest_field(visibility=["read"])
    """The error code."""
    message: Optional[str] = rest_field(visibility=["read"])
    """The error message."""
    target: Optional[str] = rest_field(visibility=["read"])
    """The error target."""
    details: Optional[list["_models.ErrorDetail"]] = rest_field(visibility=["read"])
    """The error details."""
    additional_info: Optional[list["_models.ErrorAdditionalInfo"]] = rest_field(
        name="additionalInfo", visibility=["read"]
    )
    """The error additional info."""


class ErrorResponse(_Model):
    """Error response.

    :ivar error: The error object.
    :vartype error: ~azure.mgmt.previewalertrule.models.ErrorDetail
    """

    error: Optional["_models.ErrorDetail"] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The error object."""

    @overload
    def __init__(
        self,
        *,
        error: Optional["_models.ErrorDetail"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class EvaluatedPeriod(_Model):
    """Details of the evaluated period.

    :ivar timestamp: The timestamp of the evaluated period.
    :vartype timestamp: ~datetime.datetime
    :ivar high_threshold: The high threshold value for the evaluation period.
    :vartype high_threshold: float
    :ivar low_threshold: The low threshold value for the evaluation period.
    :vartype low_threshold: float
    :ivar metric_value: The metric value for the evaluation period.
    :vartype metric_value: float
    :ivar threshold_met: Indicates whether the threshold was met during the evaluation period.
    :vartype threshold_met: bool
    """

    timestamp: Optional[datetime.datetime] = rest_field(
        visibility=["read", "create", "update", "delete", "query"], format="rfc3339"
    )
    """The timestamp of the evaluated period."""
    high_threshold: Optional[float] = rest_field(
        name="highThreshold", visibility=["read", "create", "update", "delete", "query"]
    )
    """The high threshold value for the evaluation period."""
    low_threshold: Optional[float] = rest_field(
        name="lowThreshold", visibility=["read", "create", "update", "delete", "query"]
    )
    """The low threshold value for the evaluation period."""
    metric_value: Optional[float] = rest_field(
        name="metricValue", visibility=["read", "create", "update", "delete", "query"]
    )
    """The metric value for the evaluation period."""
    threshold_met: Optional[bool] = rest_field(
        name="thresholdMet", visibility=["read", "create", "update", "delete", "query"]
    )
    """Indicates whether the threshold was met during the evaluation period."""

    @overload
    def __init__(
        self,
        *,
        timestamp: Optional[datetime.datetime] = None,
        high_threshold: Optional[float] = None,
        low_threshold: Optional[float] = None,
        metric_value: Optional[float] = None,
        threshold_met: Optional[bool] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class Evaluation(_Model):
    """An evaluation of the alert rule.

    :ivar evaluation_time: The time when the evaluation was performed.
    :vartype evaluation_time: ~datetime.datetime
    :ivar alert_state: The state of the alert after the evaluation. Known values are: "NoAlert",
     "Fired", "Firing", "Resolving", and "Resolved".
    :vartype alert_state: str or ~azure.mgmt.previewalertrule.models.AlertState
    :ivar evaluated_periods: An array of evaluated periods.
    :vartype evaluated_periods: list[~azure.mgmt.previewalertrule.models.EvaluatedPeriod]
    :ivar threshold_met: Indicates whether the threshold was met for this evaluation.
    :vartype threshold_met: bool
    """

    evaluation_time: Optional[datetime.datetime] = rest_field(
        name="evaluationTime", visibility=["read", "create", "update", "delete", "query"], format="rfc3339"
    )
    """The time when the evaluation was performed."""
    alert_state: Optional[Union[str, "_models.AlertState"]] = rest_field(
        name="alertState", visibility=["read", "create", "update", "delete", "query"]
    )
    """The state of the alert after the evaluation. Known values are: \"NoAlert\", \"Fired\",
     \"Firing\", \"Resolving\", and \"Resolved\"."""
    evaluated_periods: Optional[list["_models.EvaluatedPeriod"]] = rest_field(
        name="evaluatedPeriods", visibility=["read", "create", "update", "delete", "query"]
    )
    """An array of evaluated periods."""
    threshold_met: Optional[bool] = rest_field(
        name="thresholdMet", visibility=["read", "create", "update", "delete", "query"]
    )
    """Indicates whether the threshold was met for this evaluation."""

    @overload
    def __init__(
        self,
        *,
        evaluation_time: Optional[datetime.datetime] = None,
        alert_state: Optional[Union[str, "_models.AlertState"]] = None,
        evaluated_periods: Optional[list["_models.EvaluatedPeriod"]] = None,
        threshold_met: Optional[bool] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class LogAlertRuleCondition(_Model):
    """A condition of the scheduled query rule.

    :ivar criterion_type: Specifies the type of threshold criteria. Known values are:
     "StaticThresholdCriterion" and "DynamicThresholdCriterion".
    :vartype criterion_type: str or ~azure.mgmt.previewalertrule.models.CriterionType
    :ivar query: KQL log query alert.
    :vartype query: str
    :ivar time_aggregation: Aggregation type. Relevant and required only for rules of the kind
     LogAlert. Known values are: "Count", "Average", "Minimum", "Maximum", and "Total".
    :vartype time_aggregation: str or ~azure.mgmt.previewalertrule.models.TimeAggregation
    :ivar metric_measure_column: The column containing the metric measure number. Relevant only for
     rules of the kind LogAlert.
    :vartype metric_measure_column: str
    :ivar resource_id_column: The column containing the resource id. The content of the column must
     be a uri formatted as resource id. Relevant only for rules of the kind LogAlert.
    :vartype resource_id_column: str
    :ivar dimensions: List of Dimensions conditions.
    :vartype dimensions: list[~azure.mgmt.previewalertrule.models.LogAlertRuleDimension]
    :ivar operator: The criteria operator. Relevant and required only for rules of the kind
     LogAlert. Known values are: "Equals", "GreaterThan", "GreaterThanOrEqual", "LessThan",
     "LessThanOrEqual", and "GreaterOrLessThan".
    :vartype operator: str or ~azure.mgmt.previewalertrule.models.ConditionOperator
    :ivar threshold: the criteria threshold value that activates the alert. Relevant and required
     only for static threshold rules of the kind LogAlert.
    :vartype threshold: float
    :ivar alert_sensitivity: The extent of deviation required to trigger an alert. Allowed values
     are 'Low', 'Medium' and 'High'. This will affect how tight the threshold is to the metric
     series pattern. Relevant and required only for dynamic threshold rules of the kind LogAlert.
    :vartype alert_sensitivity: str
    :ivar ignore_data_before: Use this option to set the date from which to start learning the
     metric historical data and calculate the dynamic thresholds (in ISO8601 format). Relevant only
     for dynamic threshold rules of the kind LogAlert.
    :vartype ignore_data_before: ~datetime.datetime
    :ivar failing_periods: The minimum number of violations required within the selected lookback
     time window required to raise an alert. Relevant only for rules of the kind LogAlert.
    :vartype failing_periods:
     ~azure.mgmt.previewalertrule.models.LogAlertRuleConditionFailingPeriods
    :ivar metric_name: The name of the metric to be sent. Relevant and required only for rules of
     the kind LogToMetric.
    :vartype metric_name: str
    """

    criterion_type: Optional[Union[str, "_models.CriterionType"]] = rest_field(
        name="criterionType", visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies the type of threshold criteria. Known values are: \"StaticThresholdCriterion\" and
     \"DynamicThresholdCriterion\"."""
    query: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """KQL log query alert."""
    time_aggregation: Optional[Union[str, "_models.TimeAggregation"]] = rest_field(
        name="timeAggregation", visibility=["read", "create", "update", "delete", "query"]
    )
    """Aggregation type. Relevant and required only for rules of the kind LogAlert. Known values are:
     \"Count\", \"Average\", \"Minimum\", \"Maximum\", and \"Total\"."""
    metric_measure_column: Optional[str] = rest_field(
        name="metricMeasureColumn", visibility=["read", "create", "update", "delete", "query"]
    )
    """The column containing the metric measure number. Relevant only for rules of the kind LogAlert."""
    resource_id_column: Optional[str] = rest_field(
        name="resourceIdColumn", visibility=["read", "create", "update", "delete", "query"]
    )
    """The column containing the resource id. The content of the column must be a uri formatted as
     resource id. Relevant only for rules of the kind LogAlert."""
    dimensions: Optional[list["_models.LogAlertRuleDimension"]] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """List of Dimensions conditions."""
    operator: Optional[Union[str, "_models.ConditionOperator"]] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """The criteria operator. Relevant and required only for rules of the kind LogAlert. Known values
     are: \"Equals\", \"GreaterThan\", \"GreaterThanOrEqual\", \"LessThan\", \"LessThanOrEqual\",
     and \"GreaterOrLessThan\"."""
    threshold: Optional[float] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """the criteria threshold value that activates the alert. Relevant and required only for static
     threshold rules of the kind LogAlert."""
    alert_sensitivity: Optional[str] = rest_field(
        name="alertSensitivity", visibility=["read", "create", "update", "delete", "query"]
    )
    """The extent of deviation required to trigger an alert. Allowed values are 'Low', 'Medium' and
     'High'. This will affect how tight the threshold is to the metric series pattern. Relevant and
     required only for dynamic threshold rules of the kind LogAlert."""
    ignore_data_before: Optional[datetime.datetime] = rest_field(
        name="ignoreDataBefore", visibility=["read", "create", "update", "delete", "query"], format="rfc3339"
    )
    """Use this option to set the date from which to start learning the metric historical data and
     calculate the dynamic thresholds (in ISO8601 format). Relevant only for dynamic threshold rules
     of the kind LogAlert."""
    failing_periods: Optional["_models.LogAlertRuleConditionFailingPeriods"] = rest_field(
        name="failingPeriods", visibility=["read", "create", "update", "delete", "query"]
    )
    """The minimum number of violations required within the selected lookback time window required to
     raise an alert. Relevant only for rules of the kind LogAlert."""
    metric_name: Optional[str] = rest_field(
        name="metricName", visibility=["read", "create", "update", "delete", "query"]
    )
    """The name of the metric to be sent. Relevant and required only for rules of the kind
     LogToMetric."""

    @overload
    def __init__(
        self,
        *,
        criterion_type: Optional[Union[str, "_models.CriterionType"]] = None,
        query: Optional[str] = None,
        time_aggregation: Optional[Union[str, "_models.TimeAggregation"]] = None,
        metric_measure_column: Optional[str] = None,
        resource_id_column: Optional[str] = None,
        dimensions: Optional[list["_models.LogAlertRuleDimension"]] = None,
        operator: Optional[Union[str, "_models.ConditionOperator"]] = None,
        threshold: Optional[float] = None,
        alert_sensitivity: Optional[str] = None,
        ignore_data_before: Optional[datetime.datetime] = None,
        failing_periods: Optional["_models.LogAlertRuleConditionFailingPeriods"] = None,
        metric_name: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class LogAlertRuleConditionFailingPeriods(_Model):
    """The minimum number of violations required within the selected lookback time window required to
    raise an alert. Relevant only for rules of the kind LogAlert.

    :ivar number_of_evaluation_periods: The number of aggregated lookback points. The lookback time
     window is calculated based on the aggregation granularity (windowSize) and the selected number
     of aggregated points. Default value is 1.
    :vartype number_of_evaluation_periods: int
    :ivar min_failing_periods_to_alert: The number of violations to trigger an alert. Should be
     smaller or equal to numberOfEvaluationPeriods. Default value is 1.
    :vartype min_failing_periods_to_alert: int
    """

    number_of_evaluation_periods: Optional[int] = rest_field(
        name="numberOfEvaluationPeriods", visibility=["read", "create", "update", "delete", "query"]
    )
    """The number of aggregated lookback points. The lookback time window is calculated based on the
     aggregation granularity (windowSize) and the selected number of aggregated points. Default
     value is 1."""
    min_failing_periods_to_alert: Optional[int] = rest_field(
        name="minFailingPeriodsToAlert", visibility=["read", "create", "update", "delete", "query"]
    )
    """The number of violations to trigger an alert. Should be smaller or equal to
     numberOfEvaluationPeriods. Default value is 1."""

    @overload
    def __init__(
        self,
        *,
        number_of_evaluation_periods: Optional[int] = None,
        min_failing_periods_to_alert: Optional[int] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class LogAlertRuleCriteria(_Model):
    """The rule criteria that defines the conditions of the scheduled query rule.

    :ivar all_of: A list of conditions to evaluate against the specified scopes.
    :vartype all_of: list[~azure.mgmt.previewalertrule.models.LogAlertRuleCondition]
    """

    all_of: Optional[list["_models.LogAlertRuleCondition"]] = rest_field(
        name="allOf", visibility=["read", "create", "update", "delete", "query"]
    )
    """A list of conditions to evaluate against the specified scopes."""

    @overload
    def __init__(
        self,
        *,
        all_of: Optional[list["_models.LogAlertRuleCondition"]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class LogAlertRuleDimension(_Model):
    """Dimension splitting and filtering definition.

    :ivar name: Name of the dimension. Required.
    :vartype name: str
    :ivar operator: Operator for dimension values. Required. Known values are: "Include" and
     "Exclude".
    :vartype operator: str or ~azure.mgmt.previewalertrule.models.DimensionOperator
    :ivar values_property: List of dimension values. Required.
    :vartype values_property: list[str]
    """

    name: str = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Name of the dimension. Required."""
    operator: Union[str, "_models.DimensionOperator"] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """Operator for dimension values. Required. Known values are: \"Include\" and \"Exclude\"."""
    values_property: list[str] = rest_field(
        name="values", visibility=["read", "create", "update", "delete", "query"], original_tsp_name="values"
    )
    """List of dimension values. Required."""

    @overload
    def __init__(
        self,
        *,
        name: str,
        operator: Union[str, "_models.DimensionOperator"],
        values_property: list[str],
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class LogAlertRuleProperties(_Model):
    """scheduled query rule Definition.

    :ivar description: The description of the scheduled query rule.
    :vartype description: str
    :ivar display_name: The display name of the alert rule.
    :vartype display_name: str
    :ivar severity: Severity of the alert. Should be an integer between [0-4]. Value of 0 is
     severest. Relevant and required only for rules of the kind LogAlert. Known values are: 0, 1, 2,
     3, and 4.
    :vartype severity: float or ~azure.mgmt.previewalertrule.models.AlertSeverity
    :ivar enabled: The flag which indicates whether this scheduled query rule is enabled. Value
     should be true or false.
    :vartype enabled: bool
    :ivar scopes: The list of resource id's that this scheduled query rule is scoped to.
    :vartype scopes: list[str]
    :ivar evaluation_frequency: How often the scheduled query rule is evaluated represented in ISO
     8601 duration format. Relevant and required only for rules of the kind LogAlert.
    :vartype evaluation_frequency: ~datetime.timedelta
    :ivar window_size: The period of time (in ISO 8601 duration format) on which the Alert query
     will be executed (bin size). Relevant and required only for rules of the kind LogAlert.
    :vartype window_size: ~datetime.timedelta
    :ivar override_query_time_range: If specified then overrides the query time range (default is
     WindowSize*NumberOfEvaluationPeriods). Relevant only for rules of the kind LogAlert.
    :vartype override_query_time_range: ~datetime.timedelta
    :ivar target_resource_types: List of resource type of the target resource(s) on which the alert
     is created/updated. For example if the scope is a resource group and targetResourceTypes is
     Microsoft.Compute/virtualMachines, then a different alert will be fired for each virtual
     machine in the resource group which meet the alert criteria. Relevant only for rules of the
     kind LogAlert.
    :vartype target_resource_types: list[str]
    :ivar criteria: The rule criteria that defines the conditions of the scheduled query rule.
    :vartype criteria: ~azure.mgmt.previewalertrule.models.LogAlertRuleCriteria
    """

    description: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The description of the scheduled query rule."""
    display_name: Optional[str] = rest_field(
        name="displayName", visibility=["read", "create", "update", "delete", "query"]
    )
    """The display name of the alert rule."""
    severity: Optional[Union[float, "_models.AlertSeverity"]] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """Severity of the alert. Should be an integer between [0-4]. Value of 0 is severest. Relevant and
     required only for rules of the kind LogAlert. Known values are: 0, 1, 2, 3, and 4."""
    enabled: Optional[bool] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The flag which indicates whether this scheduled query rule is enabled. Value should be true or
     false."""
    scopes: Optional[list[str]] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The list of resource id's that this scheduled query rule is scoped to."""
    evaluation_frequency: Optional[datetime.timedelta] = rest_field(
        name="evaluationFrequency", visibility=["read", "create", "update", "delete", "query"]
    )
    """How often the scheduled query rule is evaluated represented in ISO 8601 duration format.
     Relevant and required only for rules of the kind LogAlert."""
    window_size: Optional[datetime.timedelta] = rest_field(
        name="windowSize", visibility=["read", "create", "update", "delete", "query"]
    )
    """The period of time (in ISO 8601 duration format) on which the Alert query will be executed (bin
     size). Relevant and required only for rules of the kind LogAlert."""
    override_query_time_range: Optional[datetime.timedelta] = rest_field(
        name="overrideQueryTimeRange", visibility=["read", "create", "update", "delete", "query"]
    )
    """If specified then overrides the query time range (default is
     WindowSize*NumberOfEvaluationPeriods). Relevant only for rules of the kind LogAlert."""
    target_resource_types: Optional[list[str]] = rest_field(
        name="targetResourceTypes", visibility=["read", "create", "update", "delete", "query"]
    )
    """List of resource type of the target resource(s) on which the alert is created/updated. For
     example if the scope is a resource group and targetResourceTypes is
     Microsoft.Compute/virtualMachines, then a different alert will be fired for each virtual
     machine in the resource group which meet the alert criteria. Relevant only for rules of the
     kind LogAlert."""
    criteria: Optional["_models.LogAlertRuleCriteria"] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """The rule criteria that defines the conditions of the scheduled query rule."""

    @overload
    def __init__(
        self,
        *,
        description: Optional[str] = None,
        display_name: Optional[str] = None,
        severity: Optional[Union[float, "_models.AlertSeverity"]] = None,
        enabled: Optional[bool] = None,
        scopes: Optional[list[str]] = None,
        evaluation_frequency: Optional[datetime.timedelta] = None,
        window_size: Optional[datetime.timedelta] = None,
        override_query_time_range: Optional[datetime.timedelta] = None,
        target_resource_types: Optional[list[str]] = None,
        criteria: Optional["_models.LogAlertRuleCriteria"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class LogAlertRuleResource(_Model):
    """The scheduled query rule resource.

    :ivar tags: Resource tags.
    :vartype tags: dict[str, str]
    :ivar location: The geo-location where the resource lives. Required.
    :vartype location: str
    :ivar kind: Indicates the type of scheduled query rule. The default is LogAlert. Known values
     are: "LogAlert", "EventLogAlert", and "LogToMetric".
    :vartype kind: str or ~azure.mgmt.previewalertrule.models.Kind
    :ivar properties: The rule properties of the resource. Required.
    :vartype properties: ~azure.mgmt.previewalertrule.models.LogAlertRuleProperties
    """

    tags: Optional[dict[str, str]] = rest_field(visibility=["read", "create", "update"])
    """Resource tags."""
    location: str = rest_field(visibility=["read", "create"])
    """The geo-location where the resource lives. Required."""
    kind: Optional[Union[str, "_models.Kind"]] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Indicates the type of scheduled query rule. The default is LogAlert. Known values are:
     \"LogAlert\", \"EventLogAlert\", and \"LogToMetric\"."""
    properties: "_models.LogAlertRuleProperties" = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """The rule properties of the resource. Required."""

    __flattened_items = [
        "description",
        "display_name",
        "severity",
        "enabled",
        "scopes",
        "evaluation_frequency",
        "window_size",
        "override_query_time_range",
        "target_resource_types",
        "criteria",
    ]

    @overload
    def __init__(
        self,
        *,
        location: str,
        properties: "_models.LogAlertRuleProperties",
        tags: Optional[dict[str, str]] = None,
        kind: Optional[Union[str, "_models.Kind"]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        _flattened_input = {k: kwargs.pop(k) for k in kwargs.keys() & self.__flattened_items}
        super().__init__(*args, **kwargs)
        for k, v in _flattened_input.items():
            setattr(self, k, v)

    def __getattr__(self, name: str) -> Any:
        if name in self.__flattened_items:
            if self.properties is None:
                return None
            return getattr(self.properties, name)
        raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{name}'")

    def __setattr__(self, key: str, value: Any) -> None:
        if key in self.__flattened_items:
            if self.properties is None:
                self.properties = self._attr_to_rest_field["properties"]._class_type()
            setattr(self.properties, key, value)
        else:
            super().__setattr__(key, value)


class PreviewAlertRuleRequest(_Model):
    """PreviewAlertRuleRequest.

    :ivar location: The location of the rule resource. Required.
    :vartype location: str
    :ivar properties: Required.
    :vartype properties: ~azure.mgmt.previewalertrule.models.PreviewAlertRuleRequestProperties
    """

    location: str = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The location of the rule resource. Required."""
    properties: "_models.PreviewAlertRuleRequestProperties" = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """Required."""

    @overload
    def __init__(
        self,
        *,
        location: str,
        properties: "_models.PreviewAlertRuleRequestProperties",
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class PreviewAlertRuleRequestProperties(_Model):
    """PreviewAlertRuleRequestProperties.

    :ivar timespan: Specifies the timespan of the preview in ISO 8601 duration format. Required.
    :vartype timespan: ~datetime.timedelta
    :ivar scheduled_query_rule_properties: The properties of the alert rule to preview.
    :vartype scheduled_query_rule_properties:
     ~azure.mgmt.previewalertrule.models.LogAlertRuleResource
    """

    timespan: datetime.timedelta = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Specifies the timespan of the preview in ISO 8601 duration format. Required."""
    scheduled_query_rule_properties: Optional["_models.LogAlertRuleResource"] = rest_field(
        name="scheduledQueryRuleProperties", visibility=["read", "create", "update", "delete", "query"]
    )
    """The properties of the alert rule to preview."""

    @overload
    def __init__(
        self,
        *,
        timespan: datetime.timedelta,
        scheduled_query_rule_properties: Optional["_models.LogAlertRuleResource"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class PreviewAlertRuleResponse(_Model):
    """PreviewAlertRuleResponse.

    :ivar rule_preview_results: An array of rule preview results.
    :vartype rule_preview_results: list[~azure.mgmt.previewalertrule.models.RulePreviewResult]
    """

    rule_preview_results: Optional[list["_models.RulePreviewResult"]] = rest_field(
        name="rulePreviewResults", visibility=["read", "create", "update", "delete", "query"]
    )
    """An array of rule preview results."""

    @overload
    def __init__(
        self,
        *,
        rule_preview_results: Optional[list["_models.RulePreviewResult"]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class RulePreviewResult(_Model):
    """A rule preview result containing a dimension combination and an array of evaluations.

    :ivar dimension_combination: The list of dimensions for the evaluation.
    :vartype dimension_combination: list[~azure.mgmt.previewalertrule.models.DimensionNameAndValue]
    :ivar evaluations: An array of evaluations.
    :vartype evaluations: list[~azure.mgmt.previewalertrule.models.Evaluation]
    """

    dimension_combination: Optional[list["_models.DimensionNameAndValue"]] = rest_field(
        name="dimensionCombination", visibility=["read", "create", "update", "delete", "query"]
    )
    """The list of dimensions for the evaluation."""
    evaluations: Optional[list["_models.Evaluation"]] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """An array of evaluations."""

    @overload
    def __init__(
        self,
        *,
        dimension_combination: Optional[list["_models.DimensionNameAndValue"]] = None,
        evaluations: Optional[list["_models.Evaluation"]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
