# pylint: disable=line-too-long,useless-suppression
# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# pylint: disable=wrong-import-position

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ._patch import *  # pylint: disable=unused-wildcard-import

from ._operations import Operations  # type: ignore
from ._site_network_services_operations import SiteNetworkServicesOperations  # type: ignore
from ._configuration_group_values_operations import ConfigurationGroupValuesOperations  # type: ignore
from ._network_functions_operations import NetworkFunctionsOperations  # type: ignore
from ._publishers_operations import PublishersOperations  # type: ignore
from ._sites_operations import SitesOperations  # type: ignore
from ._components_operations import ComponentsOperations  # type: ignore
from ._artifact_stores_operations import ArtifactStoresOperations  # type: ignore
from ._artifact_manifests_operations import ArtifactManifestsOperations  # type: ignore
from ._proxy_artifact_operations import ProxyArtifactOperations  # type: ignore
from ._configuration_group_schemas_operations import ConfigurationGroupSchemasOperations  # type: ignore
from ._network_function_definition_groups_operations import NetworkFunctionDefinitionGroupsOperations  # type: ignore
from ._network_function_definition_versions_operations import NetworkFunctionDefinitionVersionsOperations  # type: ignore
from ._network_service_design_groups_operations import NetworkServiceDesignGroupsOperations  # type: ignore
from ._network_service_design_versions_operations import NetworkServiceDesignVersionsOperations  # type: ignore

from ._patch import __all__ as _patch_all
from ._patch import *
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "Operations",
    "SiteNetworkServicesOperations",
    "ConfigurationGroupValuesOperations",
    "NetworkFunctionsOperations",
    "PublishersOperations",
    "SitesOperations",
    "ComponentsOperations",
    "ArtifactStoresOperations",
    "ArtifactManifestsOperations",
    "ProxyArtifactOperations",
    "ConfigurationGroupSchemasOperations",
    "NetworkFunctionDefinitionGroupsOperations",
    "NetworkFunctionDefinitionVersionsOperations",
    "NetworkServiceDesignGroupsOperations",
    "NetworkServiceDesignVersionsOperations",
]
__all__.extend([p for p in _patch_all if p not in __all__])  # pyright: ignore
_patch_sdk()
