# pylint: disable=line-too-long,useless-suppression,too-many-lines
# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# pylint: disable=useless-super-delegation

import datetime
from typing import Any, Mapping, Optional, TYPE_CHECKING, Union, overload

from .._utils.model_base import Model as _Model, rest_field

if TYPE_CHECKING:
    from .. import models as _models


class Resource(_Model):
    """Resource.

    :ivar id: Fully qualified resource ID for the resource. Ex -
     /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}.
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or
     "Microsoft.Storage/storageAccounts".
    :vartype type: str
    :ivar system_data: Azure Resource Manager metadata containing createdBy and modifiedBy
     information.
    :vartype system_data: ~azure.mgmt.baremetalinfrastructure.models.SystemData
    """

    id: Optional[str] = rest_field(visibility=["read"])
    """Fully qualified resource ID for the resource. Ex -
     /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}."""
    name: Optional[str] = rest_field(visibility=["read"])
    """The name of the resource."""
    type: Optional[str] = rest_field(visibility=["read"])
    """The type of the resource. E.g. \"Microsoft.Compute/virtualMachines\" or
     \"Microsoft.Storage/storageAccounts\"."""
    system_data: Optional["_models.SystemData"] = rest_field(name="systemData", visibility=["read"])
    """Azure Resource Manager metadata containing createdBy and modifiedBy information."""


class TrackedResource(Resource):
    """Tracked Resource.

    :ivar id: Fully qualified resource ID for the resource. Ex -
     /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}.
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or
     "Microsoft.Storage/storageAccounts".
    :vartype type: str
    :ivar system_data: Azure Resource Manager metadata containing createdBy and modifiedBy
     information.
    :vartype system_data: ~azure.mgmt.baremetalinfrastructure.models.SystemData
    :ivar tags: Resource tags.
    :vartype tags: dict[str, str]
    :ivar location: The geo-location where the resource lives. Required.
    :vartype location: str
    """

    tags: Optional[dict[str, str]] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Resource tags."""
    location: str = rest_field(visibility=["read", "create"])
    """The geo-location where the resource lives. Required."""

    @overload
    def __init__(
        self,
        *,
        location: str,
        tags: Optional[dict[str, str]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class AzureBareMetalInstance(TrackedResource):
    """AzureBareMetal instance info on Azure (ARM properties and AzureBareMetal properties).

    :ivar id: Fully qualified resource ID for the resource. Ex -
     /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}.
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or
     "Microsoft.Storage/storageAccounts".
    :vartype type: str
    :ivar system_data: Azure Resource Manager metadata containing createdBy and modifiedBy
     information.
    :vartype system_data: ~azure.mgmt.baremetalinfrastructure.models.SystemData
    :ivar tags: Resource tags.
    :vartype tags: dict[str, str]
    :ivar location: The geo-location where the resource lives. Required.
    :vartype location: str
    :ivar properties: AzureBareMetal instance properties.
    :vartype properties:
     ~azure.mgmt.baremetalinfrastructure.models.AzureBareMetalInstanceProperties
    """

    properties: Optional["_models.AzureBareMetalInstanceProperties"] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """AzureBareMetal instance properties."""

    __flattened_items = [
        "hardware_profile",
        "storage_profile",
        "os_profile",
        "network_profile",
        "azure_bare_metal_instance_id",
        "power_state",
        "proximity_placement_group",
        "hw_revision",
        "partner_node_id",
        "provisioning_state",
    ]

    @overload
    def __init__(
        self,
        *,
        location: str,
        tags: Optional[dict[str, str]] = None,
        properties: Optional["_models.AzureBareMetalInstanceProperties"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        _flattened_input = {k: kwargs.pop(k) for k in kwargs.keys() & self.__flattened_items}
        super().__init__(*args, **kwargs)
        for k, v in _flattened_input.items():
            setattr(self, k, v)

    def __getattr__(self, name: str) -> Any:
        if name in self.__flattened_items:
            if self.properties is None:
                return None
            return getattr(self.properties, name)
        raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{name}'")

    def __setattr__(self, key: str, value: Any) -> None:
        if key in self.__flattened_items:
            if self.properties is None:
                self.properties = self._attr_to_rest_field["properties"]._class_type()
            setattr(self.properties, key, value)
        else:
            super().__setattr__(key, value)


class AzureBareMetalInstanceProperties(_Model):
    """Describes the properties of an Azure Bare Metal Instance.

    :ivar hardware_profile: Specifies the hardware settings for the Azure Bare Metal Instance.
    :vartype hardware_profile: ~azure.mgmt.baremetalinfrastructure.models.HardwareProfile
    :ivar storage_profile: Specifies the storage settings for the Azure Bare Metal Instance disks.
    :vartype storage_profile: ~azure.mgmt.baremetalinfrastructure.models.StorageProfile
    :ivar os_profile: Specifies the operating system settings for the Azure Bare Metal Instance.
    :vartype os_profile: ~azure.mgmt.baremetalinfrastructure.models.OSProfile
    :ivar network_profile: Specifies the network settings for the Azure Bare Metal Instance.
    :vartype network_profile: ~azure.mgmt.baremetalinfrastructure.models.NetworkProfile
    :ivar azure_bare_metal_instance_id: Specifies the Azure Bare Metal Instance unique ID.
    :vartype azure_bare_metal_instance_id: str
    :ivar power_state: Resource power state. Known values are: "starting", "started", "stopping",
     "stopped", "restarting", and "unknown".
    :vartype power_state: str or
     ~azure.mgmt.baremetalinfrastructure.models.AzureBareMetalInstancePowerStateEnum
    :ivar proximity_placement_group: Resource proximity placement group.
    :vartype proximity_placement_group: str
    :ivar hw_revision: Hardware revision of an Azure Bare Metal Instance.
    :vartype hw_revision: str
    :ivar partner_node_id: ARM ID of another AzureBareMetalInstance that will share a network with
     this AzureBareMetalInstance.
    :vartype partner_node_id: str
    :ivar provisioning_state: State of provisioning of the AzureBareMetalInstance. Known values
     are: "Accepted", "Creating", "Updating", "Failed", "Succeeded", "Deleting", and "Migrating".
    :vartype provisioning_state: str or
     ~azure.mgmt.baremetalinfrastructure.models.AzureBareMetalProvisioningStatesEnum
    """

    hardware_profile: Optional["_models.HardwareProfile"] = rest_field(
        name="hardwareProfile", visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies the hardware settings for the Azure Bare Metal Instance."""
    storage_profile: Optional["_models.StorageProfile"] = rest_field(
        name="storageProfile", visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies the storage settings for the Azure Bare Metal Instance disks."""
    os_profile: Optional["_models.OSProfile"] = rest_field(
        name="osProfile", visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies the operating system settings for the Azure Bare Metal Instance."""
    network_profile: Optional["_models.NetworkProfile"] = rest_field(
        name="networkProfile", visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies the network settings for the Azure Bare Metal Instance."""
    azure_bare_metal_instance_id: Optional[str] = rest_field(
        name="azureBareMetalInstanceId", visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies the Azure Bare Metal Instance unique ID."""
    power_state: Optional[Union[str, "_models.AzureBareMetalInstancePowerStateEnum"]] = rest_field(
        name="powerState", visibility=["read", "create", "update", "delete", "query"]
    )
    """Resource power state. Known values are: \"starting\", \"started\", \"stopping\", \"stopped\",
     \"restarting\", and \"unknown\"."""
    proximity_placement_group: Optional[str] = rest_field(
        name="proximityPlacementGroup", visibility=["read", "create", "update", "delete", "query"]
    )
    """Resource proximity placement group."""
    hw_revision: Optional[str] = rest_field(
        name="hwRevision", visibility=["read", "create", "update", "delete", "query"]
    )
    """Hardware revision of an Azure Bare Metal Instance."""
    partner_node_id: Optional[str] = rest_field(
        name="partnerNodeId", visibility=["read", "create", "update", "delete", "query"]
    )
    """ARM ID of another AzureBareMetalInstance that will share a network with this
     AzureBareMetalInstance."""
    provisioning_state: Optional[Union[str, "_models.AzureBareMetalProvisioningStatesEnum"]] = rest_field(
        name="provisioningState", visibility=["read"]
    )
    """State of provisioning of the AzureBareMetalInstance. Known values are: \"Accepted\",
     \"Creating\", \"Updating\", \"Failed\", \"Succeeded\", \"Deleting\", and \"Migrating\"."""

    @overload
    def __init__(
        self,
        *,
        hardware_profile: Optional["_models.HardwareProfile"] = None,
        storage_profile: Optional["_models.StorageProfile"] = None,
        os_profile: Optional["_models.OSProfile"] = None,
        network_profile: Optional["_models.NetworkProfile"] = None,
        azure_bare_metal_instance_id: Optional[str] = None,
        power_state: Optional[Union[str, "_models.AzureBareMetalInstancePowerStateEnum"]] = None,
        proximity_placement_group: Optional[str] = None,
        hw_revision: Optional[str] = None,
        partner_node_id: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class AzureBareMetalStorageInstance(TrackedResource):
    """AzureBareMetalStorageInstance info on Azure (ARM properties and AzureBareMetalStorage
    properties).

    :ivar id: Fully qualified resource ID for the resource. Ex -
     /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}.
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or
     "Microsoft.Storage/storageAccounts".
    :vartype type: str
    :ivar system_data: Azure Resource Manager metadata containing createdBy and modifiedBy
     information.
    :vartype system_data: ~azure.mgmt.baremetalinfrastructure.models.SystemData
    :ivar tags: Resource tags.
    :vartype tags: dict[str, str]
    :ivar location: The geo-location where the resource lives. Required.
    :vartype location: str
    :ivar properties: AzureBareMetalStorageInstance properties.
    :vartype properties:
     ~azure.mgmt.baremetalinfrastructure.models.AzureBareMetalStorageInstanceProperties
    :ivar identity: The identity of Azure Bare Metal Storage Instance, if configured.
    :vartype identity:
     ~azure.mgmt.baremetalinfrastructure.models.AzureBareMetalStorageInstanceIdentity
    """

    properties: Optional["_models.AzureBareMetalStorageInstanceProperties"] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """AzureBareMetalStorageInstance properties."""
    identity: Optional["_models.AzureBareMetalStorageInstanceIdentity"] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """The identity of Azure Bare Metal Storage Instance, if configured."""

    __flattened_items = ["azure_bare_metal_storage_instance_unique_identifier", "storage_properties"]

    @overload
    def __init__(
        self,
        *,
        location: str,
        tags: Optional[dict[str, str]] = None,
        properties: Optional["_models.AzureBareMetalStorageInstanceProperties"] = None,
        identity: Optional["_models.AzureBareMetalStorageInstanceIdentity"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        _flattened_input = {k: kwargs.pop(k) for k in kwargs.keys() & self.__flattened_items}
        super().__init__(*args, **kwargs)
        for k, v in _flattened_input.items():
            setattr(self, k, v)

    def __getattr__(self, name: str) -> Any:
        if name in self.__flattened_items:
            if self.properties is None:
                return None
            return getattr(self.properties, name)
        raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{name}'")

    def __setattr__(self, key: str, value: Any) -> None:
        if key in self.__flattened_items:
            if self.properties is None:
                self.properties = self._attr_to_rest_field["properties"]._class_type()
            setattr(self.properties, key, value)
        else:
            super().__setattr__(key, value)


class AzureBareMetalStorageInstanceBody(_Model):
    """properties of body during PUT/PATCH for an AzureBareMetalStorageInstance.

    :ivar identity: The identity of Azure Bare Metal Storage Instance, if configured.
    :vartype identity:
     ~azure.mgmt.baremetalinfrastructure.models.AzureBareMetalStorageInstanceIdentity
    :ivar tags: Tags field of the AzureBareMetal/AzureBareMetaStorage instance.
    :vartype tags: dict[str, str]
    """

    identity: Optional["_models.AzureBareMetalStorageInstanceIdentity"] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """The identity of Azure Bare Metal Storage Instance, if configured."""
    tags: Optional[dict[str, str]] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Tags field of the AzureBareMetal/AzureBareMetaStorage instance."""

    @overload
    def __init__(
        self,
        *,
        identity: Optional["_models.AzureBareMetalStorageInstanceIdentity"] = None,
        tags: Optional[dict[str, str]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class AzureBareMetalStorageInstanceIdentity(_Model):
    """Identity for Azure Bare Metal Storage Instance.

    :ivar principal_id: The principal ID of Azure Bare Metal Storage Instance identity. This
     property will only be provided for a system assigned identity.
    :vartype principal_id: str
    :ivar tenant_id: The tenant ID associated with the Azure Bare Metal Storage Instance. This
     property will only be provided for a system assigned identity.
    :vartype tenant_id: str
    :ivar type: The type of identity used for the Azure Bare Metal Storage Instance. The type
     'SystemAssigned' refers to an implicitly created identity. The type 'None' will remove any
     identities from the Azure Bare Metal Storage Instance. Known values are: "SystemAssigned" and
     "None".
    :vartype type: str or ~azure.mgmt.baremetalinfrastructure.models.ResourceIdentityType
    """

    principal_id: Optional[str] = rest_field(name="principalId", visibility=["read"])
    """The principal ID of Azure Bare Metal Storage Instance identity. This property will only be
     provided for a system assigned identity."""
    tenant_id: Optional[str] = rest_field(name="tenantId", visibility=["read"])
    """The tenant ID associated with the Azure Bare Metal Storage Instance. This property will only be
     provided for a system assigned identity."""
    type: Optional[Union[str, "_models.ResourceIdentityType"]] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """The type of identity used for the Azure Bare Metal Storage Instance. The type 'SystemAssigned'
     refers to an implicitly created identity. The type 'None' will remove any identities from the
     Azure Bare Metal Storage Instance. Known values are: \"SystemAssigned\" and \"None\"."""

    @overload
    def __init__(
        self,
        *,
        type: Optional[Union[str, "_models.ResourceIdentityType"]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class AzureBareMetalStorageInstanceProperties(_Model):
    """Describes the properties of an AzureBareMetalStorageInstance.

    :ivar azure_bare_metal_storage_instance_unique_identifier: Specifies the
     AzureBareMetaStorageInstance unique ID.
    :vartype azure_bare_metal_storage_instance_unique_identifier: str
    :ivar storage_properties: Specifies the storage properties for the AzureBareMetalStorage
     instance.
    :vartype storage_properties: ~azure.mgmt.baremetalinfrastructure.models.StorageProperties
    """

    azure_bare_metal_storage_instance_unique_identifier: Optional[str] = rest_field(
        name="azureBareMetalStorageInstanceUniqueIdentifier", visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies the AzureBareMetaStorageInstance unique ID."""
    storage_properties: Optional["_models.StorageProperties"] = rest_field(
        name="storageProperties", visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies the storage properties for the AzureBareMetalStorage instance."""

    @overload
    def __init__(
        self,
        *,
        azure_bare_metal_storage_instance_unique_identifier: Optional[str] = None,
        storage_properties: Optional["_models.StorageProperties"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class Disk(_Model):
    """Specifies the disk information fo the Azure Bare Metal Instance.

    :ivar name: The disk name.
    :vartype name: str
    :ivar disk_size_gb: Specifies the size of an empty data disk in gigabytes.
    :vartype disk_size_gb: int
    :ivar lun: Specifies the logical unit number of the data disk. This value is used to identify
     data disks within the VM and therefore must be unique for each data disk attached to a VM.
    :vartype lun: int
    """

    name: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The disk name."""
    disk_size_gb: Optional[int] = rest_field(
        name="diskSizeGB", visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies the size of an empty data disk in gigabytes."""
    lun: Optional[int] = rest_field(visibility=["read"])
    """Specifies the logical unit number of the data disk. This value is used to identify data disks
     within the VM and therefore must be unique for each data disk attached to a VM."""

    @overload
    def __init__(
        self,
        *,
        name: Optional[str] = None,
        disk_size_gb: Optional[int] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class ErrorAdditionalInfo(_Model):
    """The resource management error additional info.

    :ivar type: The additional info type.
    :vartype type: str
    :ivar info: The additional info.
    :vartype info: any
    """

    type: Optional[str] = rest_field(visibility=["read"])
    """The additional info type."""
    info: Optional[Any] = rest_field(visibility=["read"])
    """The additional info."""


class ErrorDetail(_Model):
    """The error detail.

    :ivar code: The error code.
    :vartype code: str
    :ivar message: The error message.
    :vartype message: str
    :ivar target: The error target.
    :vartype target: str
    :ivar details: The error details.
    :vartype details: list[~azure.mgmt.baremetalinfrastructure.models.ErrorDetail]
    :ivar additional_info: The error additional info.
    :vartype additional_info: list[~azure.mgmt.baremetalinfrastructure.models.ErrorAdditionalInfo]
    """

    code: Optional[str] = rest_field(visibility=["read"])
    """The error code."""
    message: Optional[str] = rest_field(visibility=["read"])
    """The error message."""
    target: Optional[str] = rest_field(visibility=["read"])
    """The error target."""
    details: Optional[list["_models.ErrorDetail"]] = rest_field(visibility=["read"])
    """The error details."""
    additional_info: Optional[list["_models.ErrorAdditionalInfo"]] = rest_field(
        name="additionalInfo", visibility=["read"]
    )
    """The error additional info."""


class ErrorResponse(_Model):
    """Error response.

    :ivar error: The error object.
    :vartype error: ~azure.mgmt.baremetalinfrastructure.models.ErrorDetail
    """

    error: Optional["_models.ErrorDetail"] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """The error object."""

    @overload
    def __init__(
        self,
        *,
        error: Optional["_models.ErrorDetail"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class ForceState(_Model):
    """The active state empowers the server with the ability to forcefully terminate and halt any
    existing processes that may be running on the server.

    :ivar force_state: Whether to force restart by shutting all processes. Known values are:
     "active" and "inactive".
    :vartype force_state: str or
     ~azure.mgmt.baremetalinfrastructure.models.AzureBareMetalInstanceForcePowerState
    """

    force_state: Optional[Union[str, "_models.AzureBareMetalInstanceForcePowerState"]] = rest_field(
        name="forceState", visibility=["read", "create", "update", "delete", "query"]
    )
    """Whether to force restart by shutting all processes. Known values are: \"active\" and
     \"inactive\"."""

    @overload
    def __init__(
        self,
        *,
        force_state: Optional[Union[str, "_models.AzureBareMetalInstanceForcePowerState"]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class HardwareProfile(_Model):
    """Specifies the hardware settings for the Azure Bare Metal Instance.

    :ivar hardware_type: Name of the hardware type (vendor and/or their product name). Known values
     are: "Cisco_UCS", "HPE", and "SDFLEX".
    :vartype hardware_type: str or
     ~azure.mgmt.baremetalinfrastructure.models.AzureBareMetalHardwareTypeNamesEnum
    :ivar azure_bare_metal_instance_size: Specifies the Azure Bare Metal Instance SKU. Known values
     are: "S72m", "S144m", "S72", "S144", "S192", "S192m", "S192xm", "S96", "S112", "S224", "S224m",
     "S224om", "S224oo", "S224oom", "S224ooo", "S384", "S384m", "S384xm", "S384xxm", "S448",
     "S448m", "S448om", "S448oo", "S448oom", "S448ooo", "S448se", "S576m", "S576xm", "S672",
     "S672m", "S672om", "S672oo", "S672oom", "S672ooo", "S768", "S768m", "S768xm", "S896", "S896m",
     "S896om", "S896oo", "S896oom", "S896ooo", and "S960m".
    :vartype azure_bare_metal_instance_size: str or
     ~azure.mgmt.baremetalinfrastructure.models.AzureBareMetalInstanceSizeNamesEnum
    """

    hardware_type: Optional[Union[str, "_models.AzureBareMetalHardwareTypeNamesEnum"]] = rest_field(
        name="hardwareType", visibility=["read", "create", "update", "delete", "query"]
    )
    """Name of the hardware type (vendor and/or their product name). Known values are: \"Cisco_UCS\",
     \"HPE\", and \"SDFLEX\"."""
    azure_bare_metal_instance_size: Optional[Union[str, "_models.AzureBareMetalInstanceSizeNamesEnum"]] = rest_field(
        name="azureBareMetalInstanceSize", visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies the Azure Bare Metal Instance SKU. Known values are: \"S72m\", \"S144m\", \"S72\",
     \"S144\", \"S192\", \"S192m\", \"S192xm\", \"S96\", \"S112\", \"S224\", \"S224m\", \"S224om\",
     \"S224oo\", \"S224oom\", \"S224ooo\", \"S384\", \"S384m\", \"S384xm\", \"S384xxm\", \"S448\",
     \"S448m\", \"S448om\", \"S448oo\", \"S448oom\", \"S448ooo\", \"S448se\", \"S576m\", \"S576xm\",
     \"S672\", \"S672m\", \"S672om\", \"S672oo\", \"S672oom\", \"S672ooo\", \"S768\", \"S768m\",
     \"S768xm\", \"S896\", \"S896m\", \"S896om\", \"S896oo\", \"S896oom\", \"S896ooo\", and
     \"S960m\"."""

    @overload
    def __init__(
        self,
        *,
        hardware_type: Optional[Union[str, "_models.AzureBareMetalHardwareTypeNamesEnum"]] = None,
        azure_bare_metal_instance_size: Optional[Union[str, "_models.AzureBareMetalInstanceSizeNamesEnum"]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class NetworkInterface(_Model):
    """Specifies the network interfaces of a bare metal resource.

    :ivar ip_address: Specifies the IP address of the network interface.
    :vartype ip_address: str
    """

    ip_address: Optional[str] = rest_field(name="ipAddress", visibility=["read", "create", "update", "delete", "query"])
    """Specifies the IP address of the network interface."""

    @overload
    def __init__(
        self,
        *,
        ip_address: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class NetworkProfile(_Model):
    """Specifies the network settings for the Azure Bare Metal Instance disks.

    :ivar network_interfaces: Specifies the network interfaces for the Azure Bare Metal Instance.
    :vartype network_interfaces: list[~azure.mgmt.baremetalinfrastructure.models.NetworkInterface]
    :ivar circuit_id: Specifies the circuit id for connecting to express route.
    :vartype circuit_id: str
    """

    network_interfaces: Optional[list["_models.NetworkInterface"]] = rest_field(
        name="networkInterfaces", visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies the network interfaces for the Azure Bare Metal Instance."""
    circuit_id: Optional[str] = rest_field(name="circuitId", visibility=["read", "create", "update", "delete", "query"])
    """Specifies the circuit id for connecting to express route."""

    @overload
    def __init__(
        self,
        *,
        network_interfaces: Optional[list["_models.NetworkInterface"]] = None,
        circuit_id: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class Operation(_Model):
    """REST API Operation.

    :ivar name: The name of the operation, as per Resource-Based Access Control (RBAC). Examples:
     "Microsoft.Compute/virtualMachines/write", "Microsoft.Compute/virtualMachines/capture/action".
    :vartype name: str
    :ivar is_data_action: Whether the operation applies to data-plane. This is "true" for
     data-plane operations and "false" for Azure Resource Manager/control-plane operations.
    :vartype is_data_action: bool
    :ivar display: Localized display information for this particular operation.
    :vartype display: ~azure.mgmt.baremetalinfrastructure.models.OperationDisplay
    :ivar origin: The intended executor of the operation; as in Resource Based Access Control
     (RBAC) and audit logs UX. Default value is "user,system". Known values are: "user", "system",
     and "user,system".
    :vartype origin: str or ~azure.mgmt.baremetalinfrastructure.models.Origin
    :ivar action_type: Extensible enum. Indicates the action type. "Internal" refers to actions
     that are for internal only APIs. "Internal"
    :vartype action_type: str or ~azure.mgmt.baremetalinfrastructure.models.ActionType
    """

    name: Optional[str] = rest_field(visibility=["read"])
    """The name of the operation, as per Resource-Based Access Control (RBAC). Examples:
     \"Microsoft.Compute/virtualMachines/write\",
     \"Microsoft.Compute/virtualMachines/capture/action\"."""
    is_data_action: Optional[bool] = rest_field(name="isDataAction", visibility=["read"])
    """Whether the operation applies to data-plane. This is \"true\" for data-plane operations and
     \"false\" for Azure Resource Manager/control-plane operations."""
    display: Optional["_models.OperationDisplay"] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """Localized display information for this particular operation."""
    origin: Optional[Union[str, "_models.Origin"]] = rest_field(visibility=["read"])
    """The intended executor of the operation; as in Resource Based Access Control (RBAC) and audit
     logs UX. Default value is \"user,system\". Known values are: \"user\", \"system\", and
     \"user,system\"."""
    action_type: Optional[Union[str, "_models.ActionType"]] = rest_field(name="actionType", visibility=["read"])
    """Extensible enum. Indicates the action type. \"Internal\" refers to actions that are for
     internal only APIs. \"Internal\""""

    @overload
    def __init__(
        self,
        *,
        display: Optional["_models.OperationDisplay"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class OperationDisplay(_Model):
    """Localized display information for an operation.

    :ivar provider: The localized friendly form of the resource provider name, e.g. "Microsoft
     Monitoring Insights" or "Microsoft Compute".
    :vartype provider: str
    :ivar resource: The localized friendly name of the resource type related to this operation.
     E.g. "Virtual Machines" or "Job Schedule Collections".
    :vartype resource: str
    :ivar operation: The concise, localized friendly name for the operation; suitable for
     dropdowns. E.g. "Create or Update Virtual Machine", "Restart Virtual Machine".
    :vartype operation: str
    :ivar description: The short, localized friendly description of the operation; suitable for
     tool tips and detailed views.
    :vartype description: str
    """

    provider: Optional[str] = rest_field(visibility=["read"])
    """The localized friendly form of the resource provider name, e.g. \"Microsoft Monitoring
     Insights\" or \"Microsoft Compute\"."""
    resource: Optional[str] = rest_field(visibility=["read"])
    """The localized friendly name of the resource type related to this operation. E.g. \"Virtual
     Machines\" or \"Job Schedule Collections\"."""
    operation: Optional[str] = rest_field(visibility=["read"])
    """The concise, localized friendly name for the operation; suitable for dropdowns. E.g. \"Create
     or Update Virtual Machine\", \"Restart Virtual Machine\"."""
    description: Optional[str] = rest_field(visibility=["read"])
    """The short, localized friendly description of the operation; suitable for tool tips and detailed
     views."""


class OperationStatus(_Model):
    """The OperationStatus object returns the state of an asynchronous operation.

    :ivar name: Unique Operation Status Identifier.
    :vartype name: str
    :ivar status: Status of the operation. Known values are: "Requesting", "Executing",
     "Succeeded", and "Failed".
    :vartype status: str or ~azure.mgmt.baremetalinfrastructure.models.AsyncOperationStatus
    :ivar start_time: Start Time when the operation was initially executed.
    :vartype start_time: str
    :ivar error: An error from the Azure Bare Metal Infrastructure service.
    :vartype error: ~azure.mgmt.baremetalinfrastructure.models.OperationStatusError
    """

    name: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Unique Operation Status Identifier."""
    status: Optional[Union[str, "_models.AsyncOperationStatus"]] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """Status of the operation. Known values are: \"Requesting\", \"Executing\", \"Succeeded\", and
     \"Failed\"."""
    start_time: Optional[str] = rest_field(name="startTime", visibility=["read", "create", "update", "delete", "query"])
    """Start Time when the operation was initially executed."""
    error: Optional["_models.OperationStatusError"] = rest_field(
        visibility=["read", "create", "update", "delete", "query"]
    )
    """An error from the Azure Bare Metal Infrastructure service."""

    @overload
    def __init__(
        self,
        *,
        name: Optional[str] = None,
        status: Optional[Union[str, "_models.AsyncOperationStatus"]] = None,
        start_time: Optional[str] = None,
        error: Optional["_models.OperationStatusError"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class OperationStatusError(_Model):
    """An error from the Azure Bare Metal Infrastructure service.

    :ivar code: Server-defined set of error codes.
    :vartype code: str
    :ivar message: Human-readable representation of the error.
    :vartype message: str
    """

    code: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Server-defined set of error codes."""
    message: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Human-readable representation of the error."""

    @overload
    def __init__(
        self,
        *,
        code: Optional[str] = None,
        message: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class OSProfile(_Model):
    """Specifies the operating system settings for the Azure Bare Metal instance.

    :ivar computer_name: Specifies the host OS name of the Azure Bare Metal instance.
    :vartype computer_name: str
    :ivar os_type: This property allows you to specify the type of the OS.
    :vartype os_type: str
    :ivar version: Specifies version of operating system.
    :vartype version: str
    :ivar ssh_public_key: Specifies the SSH public key used to access the operating system.
    :vartype ssh_public_key: str
    """

    computer_name: Optional[str] = rest_field(
        name="computerName", visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies the host OS name of the Azure Bare Metal instance."""
    os_type: Optional[str] = rest_field(name="osType", visibility=["read", "create", "update", "delete", "query"])
    """This property allows you to specify the type of the OS."""
    version: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Specifies version of operating system."""
    ssh_public_key: Optional[str] = rest_field(
        name="sshPublicKey", visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies the SSH public key used to access the operating system."""

    @overload
    def __init__(
        self,
        *,
        computer_name: Optional[str] = None,
        os_type: Optional[str] = None,
        version: Optional[str] = None,
        ssh_public_key: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class StorageBillingProperties(_Model):
    """Describes the billing related details of the AzureBareMetalStorageInstance.

    :ivar billing_mode: the billing mode for the storage instance.
    :vartype billing_mode: str
    :ivar azure_bare_metal_storage_instance_size: the SKU type that is provisioned.
    :vartype azure_bare_metal_storage_instance_size: str
    """

    billing_mode: Optional[str] = rest_field(
        name="billingMode", visibility=["read", "create", "update", "delete", "query"]
    )
    """the billing mode for the storage instance."""
    azure_bare_metal_storage_instance_size: Optional[str] = rest_field(
        name="azureBareMetalStorageInstanceSize", visibility=["read", "create", "update", "delete", "query"]
    )
    """the SKU type that is provisioned."""

    @overload
    def __init__(
        self,
        *,
        billing_mode: Optional[str] = None,
        azure_bare_metal_storage_instance_size: Optional[str] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class StorageProfile(_Model):
    """Specifies the storage settings for the Azure Bare Metal instance disks.

    :ivar nfs_ip_address: IP Address to connect to storage.
    :vartype nfs_ip_address: str
    :ivar os_disks: Specifies information about the operating system disk used by bare metal
     instance.
    :vartype os_disks: list[~azure.mgmt.baremetalinfrastructure.models.Disk]
    """

    nfs_ip_address: Optional[str] = rest_field(
        name="nfsIpAddress", visibility=["read", "create", "update", "delete", "query"]
    )
    """IP Address to connect to storage."""
    os_disks: Optional[list["_models.Disk"]] = rest_field(
        name="osDisks", visibility=["read", "create", "update", "delete", "query"]
    )
    """Specifies information about the operating system disk used by bare metal instance."""

    @overload
    def __init__(
        self,
        *,
        nfs_ip_address: Optional[str] = None,
        os_disks: Optional[list["_models.Disk"]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class StorageProperties(_Model):
    """described the storage properties of the azure bare metal storage instance.

    :ivar provisioning_state: State of provisioning of the AzureBareMetalStorageInstance. Known
     values are: "Accepted", "Creating", "Updating", "Failed", "Succeeded", "Deleting", "Canceled",
     and "Migrating".
    :vartype provisioning_state: str or
     ~azure.mgmt.baremetalinfrastructure.models.ProvisioningState
    :ivar offering_type: the offering type for which the resource is getting provisioned.
    :vartype offering_type: str
    :ivar storage_type: the storage protocol for which the resource is getting provisioned.
    :vartype storage_type: str
    :ivar generation: the kind of storage instance.
    :vartype generation: str
    :ivar hardware_type: the hardware type of the storage instance.
    :vartype hardware_type: str
    :ivar workload_type: the workload for which the resource is getting provisioned.
    :vartype workload_type: str
    :ivar storage_billing_properties: the billing related information for the resource.
    :vartype storage_billing_properties:
     ~azure.mgmt.baremetalinfrastructure.models.StorageBillingProperties
    """

    provisioning_state: Optional[Union[str, "_models.ProvisioningState"]] = rest_field(
        name="provisioningState", visibility=["read", "create", "update", "delete", "query"]
    )
    """State of provisioning of the AzureBareMetalStorageInstance. Known values are: \"Accepted\",
     \"Creating\", \"Updating\", \"Failed\", \"Succeeded\", \"Deleting\", \"Canceled\", and
     \"Migrating\"."""
    offering_type: Optional[str] = rest_field(
        name="offeringType", visibility=["read", "create", "update", "delete", "query"]
    )
    """the offering type for which the resource is getting provisioned."""
    storage_type: Optional[str] = rest_field(
        name="storageType", visibility=["read", "create", "update", "delete", "query"]
    )
    """the storage protocol for which the resource is getting provisioned."""
    generation: Optional[str] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """the kind of storage instance."""
    hardware_type: Optional[str] = rest_field(
        name="hardwareType", visibility=["read", "create", "update", "delete", "query"]
    )
    """the hardware type of the storage instance."""
    workload_type: Optional[str] = rest_field(
        name="workloadType", visibility=["read", "create", "update", "delete", "query"]
    )
    """the workload for which the resource is getting provisioned."""
    storage_billing_properties: Optional["_models.StorageBillingProperties"] = rest_field(
        name="storageBillingProperties", visibility=["read", "create", "update", "delete", "query"]
    )
    """the billing related information for the resource."""

    @overload
    def __init__(
        self,
        *,
        provisioning_state: Optional[Union[str, "_models.ProvisioningState"]] = None,
        offering_type: Optional[str] = None,
        storage_type: Optional[str] = None,
        generation: Optional[str] = None,
        hardware_type: Optional[str] = None,
        workload_type: Optional[str] = None,
        storage_billing_properties: Optional["_models.StorageBillingProperties"] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class SystemData(_Model):
    """Metadata pertaining to creation and last modification of the resource.

    :ivar created_by: The identity that created the resource.
    :vartype created_by: str
    :ivar created_by_type: The type of identity that created the resource. Known values are:
     "User", "Application", "ManagedIdentity", and "Key".
    :vartype created_by_type: str or ~azure.mgmt.baremetalinfrastructure.models.CreatedByType
    :ivar created_at: The timestamp of resource creation (UTC).
    :vartype created_at: ~datetime.datetime
    :ivar last_modified_by: The identity that last modified the resource.
    :vartype last_modified_by: str
    :ivar last_modified_by_type: The type of identity that last modified the resource. Known values
     are: "User", "Application", "ManagedIdentity", and "Key".
    :vartype last_modified_by_type: str or ~azure.mgmt.baremetalinfrastructure.models.CreatedByType
    :ivar last_modified_at: The timestamp of resource last modification (UTC).
    :vartype last_modified_at: ~datetime.datetime
    """

    created_by: Optional[str] = rest_field(name="createdBy", visibility=["read", "create", "update", "delete", "query"])
    """The identity that created the resource."""
    created_by_type: Optional[Union[str, "_models.CreatedByType"]] = rest_field(
        name="createdByType", visibility=["read", "create", "update", "delete", "query"]
    )
    """The type of identity that created the resource. Known values are: \"User\", \"Application\",
     \"ManagedIdentity\", and \"Key\"."""
    created_at: Optional[datetime.datetime] = rest_field(
        name="createdAt", visibility=["read", "create", "update", "delete", "query"], format="rfc3339"
    )
    """The timestamp of resource creation (UTC)."""
    last_modified_by: Optional[str] = rest_field(
        name="lastModifiedBy", visibility=["read", "create", "update", "delete", "query"]
    )
    """The identity that last modified the resource."""
    last_modified_by_type: Optional[Union[str, "_models.CreatedByType"]] = rest_field(
        name="lastModifiedByType", visibility=["read", "create", "update", "delete", "query"]
    )
    """The type of identity that last modified the resource. Known values are: \"User\",
     \"Application\", \"ManagedIdentity\", and \"Key\"."""
    last_modified_at: Optional[datetime.datetime] = rest_field(
        name="lastModifiedAt", visibility=["read", "create", "update", "delete", "query"], format="rfc3339"
    )
    """The timestamp of resource last modification (UTC)."""

    @overload
    def __init__(
        self,
        *,
        created_by: Optional[str] = None,
        created_by_type: Optional[Union[str, "_models.CreatedByType"]] = None,
        created_at: Optional[datetime.datetime] = None,
        last_modified_by: Optional[str] = None,
        last_modified_by_type: Optional[Union[str, "_models.CreatedByType"]] = None,
        last_modified_at: Optional[datetime.datetime] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)


class Tags(_Model):
    """Tags field of the AzureBareMetal/AzureBareMetalStorage instance.

    :ivar tags: Tags field of the AzureBareMetal/AzureBareMetaStorage instance.
    :vartype tags: dict[str, str]
    """

    tags: Optional[dict[str, str]] = rest_field(visibility=["read", "create", "update", "delete", "query"])
    """Tags field of the AzureBareMetal/AzureBareMetaStorage instance."""

    @overload
    def __init__(
        self,
        *,
        tags: Optional[dict[str, str]] = None,
    ) -> None: ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]) -> None:
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
