# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from copy import deepcopy
from typing import Any, Optional, TYPE_CHECKING, cast
from typing_extensions import Self

from azure.core.pipeline import policies
from azure.core.rest import HttpRequest, HttpResponse
from azure.core.settings import settings
from azure.mgmt.core import ARMPipelineClient
from azure.mgmt.core.policies import ARMAutoResourceProviderRegistrationPolicy
from azure.mgmt.core.tools import get_arm_endpoints

from ._configuration import HybridNetworkManagementClientConfiguration
from ._utils.serialization import Deserializer, Serializer
from .operations import (
    ArtifactManifestsOperations,
    ArtifactStoresOperations,
    ComponentsOperations,
    ConfigurationGroupSchemasOperations,
    ConfigurationGroupValuesOperations,
    NetworkFunctionDefinitionGroupsOperations,
    NetworkFunctionDefinitionVersionsOperations,
    NetworkFunctionsOperations,
    NetworkServiceDesignGroupsOperations,
    NetworkServiceDesignVersionsOperations,
    Operations,
    ProxyArtifactOperations,
    PublishersOperations,
    SiteNetworkServicesOperations,
    SitesOperations,
)

if TYPE_CHECKING:
    from azure.core import AzureClouds
    from azure.core.credentials import TokenCredential


class HybridNetworkManagementClient:  # pylint: disable=too-many-instance-attributes
    """HybridNetworkManagementClient.

    :ivar operations: Operations operations
    :vartype operations: azure.mgmt.hybridnetwork.operations.Operations
    :ivar configuration_group_schemas: ConfigurationGroupSchemasOperations operations
    :vartype configuration_group_schemas:
     azure.mgmt.hybridnetwork.operations.ConfigurationGroupSchemasOperations
    :ivar publishers: PublishersOperations operations
    :vartype publishers: azure.mgmt.hybridnetwork.operations.PublishersOperations
    :ivar configuration_group_values: ConfigurationGroupValuesOperations operations
    :vartype configuration_group_values:
     azure.mgmt.hybridnetwork.operations.ConfigurationGroupValuesOperations
    :ivar network_functions: NetworkFunctionsOperations operations
    :vartype network_functions: azure.mgmt.hybridnetwork.operations.NetworkFunctionsOperations
    :ivar components: ComponentsOperations operations
    :vartype components: azure.mgmt.hybridnetwork.operations.ComponentsOperations
    :ivar network_function_definition_groups: NetworkFunctionDefinitionGroupsOperations operations
    :vartype network_function_definition_groups:
     azure.mgmt.hybridnetwork.operations.NetworkFunctionDefinitionGroupsOperations
    :ivar network_function_definition_versions: NetworkFunctionDefinitionVersionsOperations
     operations
    :vartype network_function_definition_versions:
     azure.mgmt.hybridnetwork.operations.NetworkFunctionDefinitionVersionsOperations
    :ivar network_service_design_groups: NetworkServiceDesignGroupsOperations operations
    :vartype network_service_design_groups:
     azure.mgmt.hybridnetwork.operations.NetworkServiceDesignGroupsOperations
    :ivar network_service_design_versions: NetworkServiceDesignVersionsOperations operations
    :vartype network_service_design_versions:
     azure.mgmt.hybridnetwork.operations.NetworkServiceDesignVersionsOperations
    :ivar artifact_stores: ArtifactStoresOperations operations
    :vartype artifact_stores: azure.mgmt.hybridnetwork.operations.ArtifactStoresOperations
    :ivar proxy_artifact: ProxyArtifactOperations operations
    :vartype proxy_artifact: azure.mgmt.hybridnetwork.operations.ProxyArtifactOperations
    :ivar artifact_manifests: ArtifactManifestsOperations operations
    :vartype artifact_manifests: azure.mgmt.hybridnetwork.operations.ArtifactManifestsOperations
    :ivar sites: SitesOperations operations
    :vartype sites: azure.mgmt.hybridnetwork.operations.SitesOperations
    :ivar site_network_services: SiteNetworkServicesOperations operations
    :vartype site_network_services:
     azure.mgmt.hybridnetwork.operations.SiteNetworkServicesOperations
    :param credential: Credential used to authenticate requests to the service. Required.
    :type credential: ~azure.core.credentials.TokenCredential
    :param subscription_id: The ID of the target subscription. The value must be an UUID. Required.
    :type subscription_id: str
    :param base_url: Service host. Default value is None.
    :type base_url: str
    :keyword cloud_setting: The cloud setting for which to get the ARM endpoint. Default value is
     None.
    :paramtype cloud_setting: ~azure.core.AzureClouds
    :keyword api_version: The API version to use for this operation. Default value is "2025-03-30".
     Note that overriding this default value may result in unsupported behavior.
    :paramtype api_version: str
    :keyword int polling_interval: Default waiting time between two polls for LRO operations if no
     Retry-After header is present.
    """

    def __init__(
        self,
        credential: "TokenCredential",
        subscription_id: str,
        base_url: Optional[str] = None,
        *,
        cloud_setting: Optional["AzureClouds"] = None,
        **kwargs: Any
    ) -> None:
        _endpoint = "{endpoint}"
        _cloud = cloud_setting or settings.current.azure_cloud  # type: ignore
        _endpoints = get_arm_endpoints(_cloud)
        if not base_url:
            base_url = _endpoints["resource_manager"]
        credential_scopes = kwargs.pop("credential_scopes", _endpoints["credential_scopes"])
        self._config = HybridNetworkManagementClientConfiguration(
            credential=credential,
            subscription_id=subscription_id,
            base_url=cast(str, base_url),
            cloud_setting=cloud_setting,
            credential_scopes=credential_scopes,
            **kwargs
        )

        _policies = kwargs.pop("policies", None)
        if _policies is None:
            _policies = [
                policies.RequestIdPolicy(**kwargs),
                self._config.headers_policy,
                self._config.user_agent_policy,
                self._config.proxy_policy,
                policies.ContentDecodePolicy(**kwargs),
                ARMAutoResourceProviderRegistrationPolicy(),
                self._config.redirect_policy,
                self._config.retry_policy,
                self._config.authentication_policy,
                self._config.custom_hook_policy,
                self._config.logging_policy,
                policies.DistributedTracingPolicy(**kwargs),
                policies.SensitiveHeaderCleanupPolicy(**kwargs) if self._config.redirect_policy else None,
                self._config.http_logging_policy,
            ]
        self._client: ARMPipelineClient = ARMPipelineClient(base_url=cast(str, _endpoint), policies=_policies, **kwargs)

        self._serialize = Serializer()
        self._deserialize = Deserializer()
        self._serialize.client_side_validation = False
        self.operations = Operations(self._client, self._config, self._serialize, self._deserialize)
        self.configuration_group_schemas = ConfigurationGroupSchemasOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.publishers = PublishersOperations(self._client, self._config, self._serialize, self._deserialize)
        self.configuration_group_values = ConfigurationGroupValuesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.network_functions = NetworkFunctionsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.components = ComponentsOperations(self._client, self._config, self._serialize, self._deserialize)
        self.network_function_definition_groups = NetworkFunctionDefinitionGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.network_function_definition_versions = NetworkFunctionDefinitionVersionsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.network_service_design_groups = NetworkServiceDesignGroupsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.network_service_design_versions = NetworkServiceDesignVersionsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.artifact_stores = ArtifactStoresOperations(self._client, self._config, self._serialize, self._deserialize)
        self.proxy_artifact = ProxyArtifactOperations(self._client, self._config, self._serialize, self._deserialize)
        self.artifact_manifests = ArtifactManifestsOperations(
            self._client, self._config, self._serialize, self._deserialize
        )
        self.sites = SitesOperations(self._client, self._config, self._serialize, self._deserialize)
        self.site_network_services = SiteNetworkServicesOperations(
            self._client, self._config, self._serialize, self._deserialize
        )

    def send_request(self, request: HttpRequest, *, stream: bool = False, **kwargs: Any) -> HttpResponse:
        """Runs the network request through the client's chained policies.

        >>> from azure.core.rest import HttpRequest
        >>> request = HttpRequest("GET", "https://www.example.org/")
        <HttpRequest [GET], url: 'https://www.example.org/'>
        >>> response = client.send_request(request)
        <HttpResponse: 200 OK>

        For more information on this code flow, see https://aka.ms/azsdk/dpcodegen/python/send_request

        :param request: The network request you want to make. Required.
        :type request: ~azure.core.rest.HttpRequest
        :keyword bool stream: Whether the response payload will be streamed. Defaults to False.
        :return: The response of your network call. Does not do error handling on your response.
        :rtype: ~azure.core.rest.HttpResponse
        """

        request_copy = deepcopy(request)
        path_format_arguments = {
            "endpoint": self._serialize.url("self._config.base_url", self._config.base_url, "str", skip_quote=True),
        }

        request_copy.url = self._client.format_url(request_copy.url, **path_format_arguments)
        return self._client.send_request(request_copy, stream=stream, **kwargs)  # type: ignore

    def close(self) -> None:
        self._client.close()

    def __enter__(self) -> Self:
        self._client.__enter__()
        return self

    def __exit__(self, *exc_details: Any) -> None:
        self._client.__exit__(*exc_details)
