# pylint: disable=line-too-long,useless-suppression,too-many-lines
# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from collections.abc import MutableMapping
import datetime
from typing import Any, Optional, TYPE_CHECKING, Union

from .._utils import serialization as _serialization

if TYPE_CHECKING:
    from .. import models as _models
JSON = MutableMapping[str, Any]


class AcceptOwnershipRequest(_serialization.Model):
    """The parameters required to accept subscription ownership.

    :ivar properties: Accept subscription ownership request properties.
    :vartype properties: ~azure.mgmt.subscription.models.AcceptOwnershipRequestProperties
    """

    _attribute_map = {
        "properties": {"key": "properties", "type": "AcceptOwnershipRequestProperties"},
    }

    def __init__(
        self, *, properties: Optional["_models.AcceptOwnershipRequestProperties"] = None, **kwargs: Any
    ) -> None:
        """
        :keyword properties: Accept subscription ownership request properties.
        :paramtype properties: ~azure.mgmt.subscription.models.AcceptOwnershipRequestProperties
        """
        super().__init__(**kwargs)
        self.properties = properties


class AcceptOwnershipRequestProperties(_serialization.Model):
    """Accept subscription ownership request properties.

    All required parameters must be populated in order to send to server.

    :ivar display_name: The friendly name of the subscription. Required.
    :vartype display_name: str
    :ivar management_group_id: Management group Id for the subscription.
    :vartype management_group_id: str
    :ivar tags: Tags for the subscription.
    :vartype tags: dict[str, str]
    """

    _validation = {
        "display_name": {"required": True},
    }

    _attribute_map = {
        "display_name": {"key": "displayName", "type": "str"},
        "management_group_id": {"key": "managementGroupId", "type": "str"},
        "tags": {"key": "tags", "type": "{str}"},
    }

    def __init__(
        self,
        *,
        display_name: str,
        management_group_id: Optional[str] = None,
        tags: Optional[dict[str, str]] = None,
        **kwargs: Any
    ) -> None:
        """
        :keyword display_name: The friendly name of the subscription. Required.
        :paramtype display_name: str
        :keyword management_group_id: Management group Id for the subscription.
        :paramtype management_group_id: str
        :keyword tags: Tags for the subscription.
        :paramtype tags: dict[str, str]
        """
        super().__init__(**kwargs)
        self.display_name = display_name
        self.management_group_id = management_group_id
        self.tags = tags


class AcceptOwnershipStatusResponse(_serialization.Model):
    """Subscription Accept Ownership Response.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar subscription_id: Newly created subscription Id.
    :vartype subscription_id: str
    :ivar accept_ownership_state: The accept ownership state of the resource. Known values are:
     "Pending", "Completed", and "Expired".
    :vartype accept_ownership_state: str or ~azure.mgmt.subscription.models.AcceptOwnership
    :ivar provisioning_state: The provisioning state of the resource. Known values are: "Pending",
     "Accepted", and "Succeeded".
    :vartype provisioning_state: str or ~azure.mgmt.subscription.models.Provisioning
    :ivar billing_owner: UPN of the billing owner.
    :vartype billing_owner: str
    :ivar subscription_tenant_id: Tenant Id of the subscription.
    :vartype subscription_tenant_id: str
    :ivar display_name: The display name of the subscription.
    :vartype display_name: str
    :ivar tags: Tags for the subscription.
    :vartype tags: dict[str, str]
    """

    _validation = {
        "subscription_id": {"readonly": True},
        "accept_ownership_state": {"readonly": True},
        "provisioning_state": {"readonly": True},
        "billing_owner": {"readonly": True},
    }

    _attribute_map = {
        "subscription_id": {"key": "subscriptionId", "type": "str"},
        "accept_ownership_state": {"key": "acceptOwnershipState", "type": "str"},
        "provisioning_state": {"key": "provisioningState", "type": "str"},
        "billing_owner": {"key": "billingOwner", "type": "str"},
        "subscription_tenant_id": {"key": "subscriptionTenantId", "type": "str"},
        "display_name": {"key": "displayName", "type": "str"},
        "tags": {"key": "tags", "type": "{str}"},
    }

    def __init__(
        self,
        *,
        subscription_tenant_id: Optional[str] = None,
        display_name: Optional[str] = None,
        tags: Optional[dict[str, str]] = None,
        **kwargs: Any
    ) -> None:
        """
        :keyword subscription_tenant_id: Tenant Id of the subscription.
        :paramtype subscription_tenant_id: str
        :keyword display_name: The display name of the subscription.
        :paramtype display_name: str
        :keyword tags: Tags for the subscription.
        :paramtype tags: dict[str, str]
        """
        super().__init__(**kwargs)
        self.subscription_id: Optional[str] = None
        self.accept_ownership_state: Optional[Union[str, "_models.AcceptOwnership"]] = None
        self.provisioning_state: Optional[Union[str, "_models.Provisioning"]] = None
        self.billing_owner: Optional[str] = None
        self.subscription_tenant_id = subscription_tenant_id
        self.display_name = display_name
        self.tags = tags


class Resource(_serialization.Model):
    """Common fields that are returned in the response for all Azure Resource Manager resources.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar id: Fully qualified resource ID for the resource. E.g.
     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}".
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or
     "Microsoft.Storage/storageAccounts".
    :vartype type: str
    :ivar system_data: Azure Resource Manager metadata containing createdBy and modifiedBy
     information.
    :vartype system_data: ~azure.mgmt.subscription.models.SystemData
    """

    _validation = {
        "id": {"readonly": True},
        "name": {"readonly": True},
        "type": {"readonly": True},
        "system_data": {"readonly": True},
    }

    _attribute_map = {
        "id": {"key": "id", "type": "str"},
        "name": {"key": "name", "type": "str"},
        "type": {"key": "type", "type": "str"},
        "system_data": {"key": "systemData", "type": "SystemData"},
    }

    def __init__(self, **kwargs: Any) -> None:
        """ """
        super().__init__(**kwargs)
        self.id: Optional[str] = None
        self.name: Optional[str] = None
        self.type: Optional[str] = None
        self.system_data: Optional["_models.SystemData"] = None


class ProxyResource(Resource):
    """The resource model definition for a Azure Resource Manager proxy resource. It will not have
    tags and a location.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar id: Fully qualified resource ID for the resource. E.g.
     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}".
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or
     "Microsoft.Storage/storageAccounts".
    :vartype type: str
    :ivar system_data: Azure Resource Manager metadata containing createdBy and modifiedBy
     information.
    :vartype system_data: ~azure.mgmt.subscription.models.SystemData
    """


class BillingAccountPoliciesResponse(ProxyResource):
    """Billing account policies information.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar id: Fully qualified resource ID for the resource. E.g.
     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}".
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or
     "Microsoft.Storage/storageAccounts".
    :vartype type: str
    :ivar system_data: Azure Resource Manager metadata containing createdBy and modifiedBy
     information.
    :vartype system_data: ~azure.mgmt.subscription.models.SystemData
    :ivar properties: Billing account policies response properties.
    :vartype properties: ~azure.mgmt.subscription.models.BillingAccountPoliciesResponseProperties
    """

    _validation = {
        "id": {"readonly": True},
        "name": {"readonly": True},
        "type": {"readonly": True},
        "system_data": {"readonly": True},
    }

    _attribute_map = {
        "id": {"key": "id", "type": "str"},
        "name": {"key": "name", "type": "str"},
        "type": {"key": "type", "type": "str"},
        "system_data": {"key": "systemData", "type": "SystemData"},
        "properties": {"key": "properties", "type": "BillingAccountPoliciesResponseProperties"},
    }

    def __init__(
        self, *, properties: Optional["_models.BillingAccountPoliciesResponseProperties"] = None, **kwargs: Any
    ) -> None:
        """
        :keyword properties: Billing account policies response properties.
        :paramtype properties: ~azure.mgmt.subscription.models.BillingAccountPoliciesResponseProperties
        """
        super().__init__(**kwargs)
        self.properties = properties


class BillingAccountPoliciesResponseProperties(_serialization.Model):
    """Put billing account policies response properties.

    :ivar service_tenants: Service tenant for the billing account.
    :vartype service_tenants: list[~azure.mgmt.subscription.models.ServiceTenantResponse]
    :ivar allow_transfers: Determine if the transfers are allowed for the billing account.
    :vartype allow_transfers: bool
    """

    _attribute_map = {
        "service_tenants": {"key": "serviceTenants", "type": "[ServiceTenantResponse]"},
        "allow_transfers": {"key": "allowTransfers", "type": "bool"},
    }

    def __init__(
        self,
        *,
        service_tenants: Optional[list["_models.ServiceTenantResponse"]] = None,
        allow_transfers: Optional[bool] = None,
        **kwargs: Any
    ) -> None:
        """
        :keyword service_tenants: Service tenant for the billing account.
        :paramtype service_tenants: list[~azure.mgmt.subscription.models.ServiceTenantResponse]
        :keyword allow_transfers: Determine if the transfers are allowed for the billing account.
        :paramtype allow_transfers: bool
        """
        super().__init__(**kwargs)
        self.service_tenants = service_tenants
        self.allow_transfers = allow_transfers


class CanceledSubscriptionId(_serialization.Model):
    """The ID of the canceled subscription.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar subscription_id: The ID of the canceled subscription.
    :vartype subscription_id: str
    """

    _validation = {
        "subscription_id": {"readonly": True},
    }

    _attribute_map = {
        "subscription_id": {"key": "subscriptionId", "type": "str"},
    }

    def __init__(self, **kwargs: Any) -> None:
        """ """
        super().__init__(**kwargs)
        self.subscription_id: Optional[str] = None


class EnabledSubscriptionId(_serialization.Model):
    """The ID of the subscriptions that is being enabled.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar subscription_id: The ID of the subscriptions that is being enabled.
    :vartype subscription_id: str
    """

    _validation = {
        "subscription_id": {"readonly": True},
    }

    _attribute_map = {
        "subscription_id": {"key": "subscriptionId", "type": "str"},
    }

    def __init__(self, **kwargs: Any) -> None:
        """ """
        super().__init__(**kwargs)
        self.subscription_id: Optional[str] = None


class ErrorAdditionalInfo(_serialization.Model):
    """The resource management error additional info.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar type: The additional info type.
    :vartype type: str
    :ivar info: The additional info.
    :vartype info: JSON
    """

    _validation = {
        "type": {"readonly": True},
        "info": {"readonly": True},
    }

    _attribute_map = {
        "type": {"key": "type", "type": "str"},
        "info": {"key": "info", "type": "object"},
    }

    def __init__(self, **kwargs: Any) -> None:
        """ """
        super().__init__(**kwargs)
        self.type: Optional[str] = None
        self.info: Optional[JSON] = None


class ErrorDetail(_serialization.Model):
    """The error detail.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar code: The error code.
    :vartype code: str
    :ivar message: The error message.
    :vartype message: str
    :ivar target: The error target.
    :vartype target: str
    :ivar details: The error details.
    :vartype details: list[~azure.mgmt.subscription.models.ErrorDetail]
    :ivar additional_info: The error additional info.
    :vartype additional_info: list[~azure.mgmt.subscription.models.ErrorAdditionalInfo]
    """

    _validation = {
        "code": {"readonly": True},
        "message": {"readonly": True},
        "target": {"readonly": True},
        "details": {"readonly": True},
        "additional_info": {"readonly": True},
    }

    _attribute_map = {
        "code": {"key": "code", "type": "str"},
        "message": {"key": "message", "type": "str"},
        "target": {"key": "target", "type": "str"},
        "details": {"key": "details", "type": "[ErrorDetail]"},
        "additional_info": {"key": "additionalInfo", "type": "[ErrorAdditionalInfo]"},
    }

    def __init__(self, **kwargs: Any) -> None:
        """ """
        super().__init__(**kwargs)
        self.code: Optional[str] = None
        self.message: Optional[str] = None
        self.target: Optional[str] = None
        self.details: Optional[list["_models.ErrorDetail"]] = None
        self.additional_info: Optional[list["_models.ErrorAdditionalInfo"]] = None


class ErrorResponse(_serialization.Model):
    """Common error response for all Azure Resource Manager APIs to return error details for failed
    operations. (This also follows the OData error response format.).

    :ivar error: The error object.
    :vartype error: ~azure.mgmt.subscription.models.ErrorDetail
    """

    _attribute_map = {
        "error": {"key": "error", "type": "ErrorDetail"},
    }

    def __init__(self, *, error: Optional["_models.ErrorDetail"] = None, **kwargs: Any) -> None:
        """
        :keyword error: The error object.
        :paramtype error: ~azure.mgmt.subscription.models.ErrorDetail
        """
        super().__init__(**kwargs)
        self.error = error


class GetTenantPolicyListResponse(_serialization.Model):
    """Tenant policy information list.

    All required parameters must be populated in order to send to server.

    :ivar value: The GetTenantPolicyResponse items on this page. Required.
    :vartype value: list[~azure.mgmt.subscription.models.GetTenantPolicyResponse]
    :ivar next_link: The link to the next page of items.
    :vartype next_link: str
    """

    _validation = {
        "value": {"required": True},
    }

    _attribute_map = {
        "value": {"key": "value", "type": "[GetTenantPolicyResponse]"},
        "next_link": {"key": "nextLink", "type": "str"},
    }

    def __init__(
        self, *, value: list["_models.GetTenantPolicyResponse"], next_link: Optional[str] = None, **kwargs: Any
    ) -> None:
        """
        :keyword value: The GetTenantPolicyResponse items on this page. Required.
        :paramtype value: list[~azure.mgmt.subscription.models.GetTenantPolicyResponse]
        :keyword next_link: The link to the next page of items.
        :paramtype next_link: str
        """
        super().__init__(**kwargs)
        self.value = value
        self.next_link = next_link


class GetTenantPolicyResponse(ProxyResource):
    """Tenant policy Information.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar id: Fully qualified resource ID for the resource. E.g.
     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}".
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or
     "Microsoft.Storage/storageAccounts".
    :vartype type: str
    :ivar system_data: Azure Resource Manager metadata containing createdBy and modifiedBy
     information.
    :vartype system_data: ~azure.mgmt.subscription.models.SystemData
    :ivar properties: Tenant policy properties.
    :vartype properties: ~azure.mgmt.subscription.models.TenantPolicy
    """

    _validation = {
        "id": {"readonly": True},
        "name": {"readonly": True},
        "type": {"readonly": True},
        "system_data": {"readonly": True},
    }

    _attribute_map = {
        "id": {"key": "id", "type": "str"},
        "name": {"key": "name", "type": "str"},
        "type": {"key": "type", "type": "str"},
        "system_data": {"key": "systemData", "type": "SystemData"},
        "properties": {"key": "properties", "type": "TenantPolicy"},
    }

    def __init__(self, *, properties: Optional["_models.TenantPolicy"] = None, **kwargs: Any) -> None:
        """
        :keyword properties: Tenant policy properties.
        :paramtype properties: ~azure.mgmt.subscription.models.TenantPolicy
        """
        super().__init__(**kwargs)
        self.properties = properties


class Operation(_serialization.Model):
    """Details of a REST API operation, returned from the Resource Provider Operations API.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar name: The name of the operation, as per Resource-Based Access Control (RBAC). Examples:
     "Microsoft.Compute/virtualMachines/write", "Microsoft.Compute/virtualMachines/capture/action".
    :vartype name: str
    :ivar is_data_action: Whether the operation applies to data-plane. This is "true" for
     data-plane operations and "false" for ARM/control-plane operations.
    :vartype is_data_action: bool
    :ivar display: Localized display information for this particular operation.
    :vartype display: ~azure.mgmt.subscription.models.OperationDisplay
    :ivar origin: The intended executor of the operation; as in Resource Based Access Control
     (RBAC) and audit logs UX. Default value is "user,system". Known values are: "user", "system",
     and "user,system".
    :vartype origin: str or ~azure.mgmt.subscription.models.Origin
    :ivar action_type: Enum. Indicates the action type. "Internal" refers to actions that are for
     internal only APIs. "Internal"
    :vartype action_type: str or ~azure.mgmt.subscription.models.ActionType
    """

    _validation = {
        "name": {"readonly": True},
        "is_data_action": {"readonly": True},
        "origin": {"readonly": True},
        "action_type": {"readonly": True},
    }

    _attribute_map = {
        "name": {"key": "name", "type": "str"},
        "is_data_action": {"key": "isDataAction", "type": "bool"},
        "display": {"key": "display", "type": "OperationDisplay"},
        "origin": {"key": "origin", "type": "str"},
        "action_type": {"key": "actionType", "type": "str"},
    }

    def __init__(self, *, display: Optional["_models.OperationDisplay"] = None, **kwargs: Any) -> None:
        """
        :keyword display: Localized display information for this particular operation.
        :paramtype display: ~azure.mgmt.subscription.models.OperationDisplay
        """
        super().__init__(**kwargs)
        self.name: Optional[str] = None
        self.is_data_action: Optional[bool] = None
        self.display = display
        self.origin: Optional[Union[str, "_models.Origin"]] = None
        self.action_type: Optional[Union[str, "_models.ActionType"]] = None


class OperationDisplay(_serialization.Model):
    """Localized display information for this particular operation.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar provider: The localized friendly form of the resource provider name, e.g. "Microsoft
     Monitoring Insights" or "Microsoft Compute".
    :vartype provider: str
    :ivar resource: The localized friendly name of the resource type related to this operation.
     E.g. "Virtual Machines" or "Job Schedule Collections".
    :vartype resource: str
    :ivar operation: The concise, localized friendly name for the operation; suitable for
     dropdowns. E.g. "Create or Update Virtual Machine", "Restart Virtual Machine".
    :vartype operation: str
    :ivar description: The short, localized friendly description of the operation; suitable for
     tool tips and detailed views.
    :vartype description: str
    """

    _validation = {
        "provider": {"readonly": True},
        "resource": {"readonly": True},
        "operation": {"readonly": True},
        "description": {"readonly": True},
    }

    _attribute_map = {
        "provider": {"key": "provider", "type": "str"},
        "resource": {"key": "resource", "type": "str"},
        "operation": {"key": "operation", "type": "str"},
        "description": {"key": "description", "type": "str"},
    }

    def __init__(self, **kwargs: Any) -> None:
        """ """
        super().__init__(**kwargs)
        self.provider: Optional[str] = None
        self.resource: Optional[str] = None
        self.operation: Optional[str] = None
        self.description: Optional[str] = None


class OperationListResult(_serialization.Model):
    """A list of REST API operations supported by an Azure Resource Provider. It contains an URL link
    to get the next set of results.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar value: List of operations supported by the resource provider.
    :vartype value: list[~azure.mgmt.subscription.models.Operation]
    :ivar next_link: URL to get the next set of operation list results (if there are any).
    :vartype next_link: str
    """

    _validation = {
        "value": {"readonly": True},
        "next_link": {"readonly": True},
    }

    _attribute_map = {
        "value": {"key": "value", "type": "[Operation]"},
        "next_link": {"key": "nextLink", "type": "str"},
    }

    def __init__(self, **kwargs: Any) -> None:
        """ """
        super().__init__(**kwargs)
        self.value: Optional[list["_models.Operation"]] = None
        self.next_link: Optional[str] = None


class PutAliasRequest(_serialization.Model):
    """The parameters required to create a new subscription.

    :ivar properties: Put alias request properties.
    :vartype properties: ~azure.mgmt.subscription.models.PutAliasRequestProperties
    """

    _attribute_map = {
        "properties": {"key": "properties", "type": "PutAliasRequestProperties"},
    }

    def __init__(self, *, properties: Optional["_models.PutAliasRequestProperties"] = None, **kwargs: Any) -> None:
        """
        :keyword properties: Put alias request properties.
        :paramtype properties: ~azure.mgmt.subscription.models.PutAliasRequestProperties
        """
        super().__init__(**kwargs)
        self.properties = properties


class PutAliasRequestAdditionalProperties(_serialization.Model):
    """Put subscription additional properties.

    :ivar management_group_id: Management group Id for the subscription.
    :vartype management_group_id: str
    :ivar subscription_tenant_id: Tenant Id of the subscription.
    :vartype subscription_tenant_id: str
    :ivar subscription_owner_id: Owner Id of the subscription.
    :vartype subscription_owner_id: str
    :ivar tags: Tags for the subscription.
    :vartype tags: dict[str, str]
    """

    _attribute_map = {
        "management_group_id": {"key": "managementGroupId", "type": "str"},
        "subscription_tenant_id": {"key": "subscriptionTenantId", "type": "str"},
        "subscription_owner_id": {"key": "subscriptionOwnerId", "type": "str"},
        "tags": {"key": "tags", "type": "{str}"},
    }

    def __init__(
        self,
        *,
        management_group_id: Optional[str] = None,
        subscription_tenant_id: Optional[str] = None,
        subscription_owner_id: Optional[str] = None,
        tags: Optional[dict[str, str]] = None,
        **kwargs: Any
    ) -> None:
        """
        :keyword management_group_id: Management group Id for the subscription.
        :paramtype management_group_id: str
        :keyword subscription_tenant_id: Tenant Id of the subscription.
        :paramtype subscription_tenant_id: str
        :keyword subscription_owner_id: Owner Id of the subscription.
        :paramtype subscription_owner_id: str
        :keyword tags: Tags for the subscription.
        :paramtype tags: dict[str, str]
        """
        super().__init__(**kwargs)
        self.management_group_id = management_group_id
        self.subscription_tenant_id = subscription_tenant_id
        self.subscription_owner_id = subscription_owner_id
        self.tags = tags


class PutAliasRequestProperties(_serialization.Model):
    """Put subscription properties.

    :ivar display_name: The friendly name of the subscription.
    :vartype display_name: str
    :ivar workload: The workload type of the subscription. It can be either Production or DevTest.
     Known values are: "Production" and "DevTest".
    :vartype workload: str or ~azure.mgmt.subscription.models.Workload
    :ivar billing_scope: Billing scope of the subscription.
     For CustomerLed and FieldLed -
     /billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/invoiceSections/{invoiceSectionName}
     For PartnerLed - /billingAccounts/{billingAccountName}/customers/{customerName}
     For Legacy EA -
     /billingAccounts/{billingAccountName}/enrollmentAccounts/{enrollmentAccountName}.
    :vartype billing_scope: str
    :ivar subscription_id: This parameter can be used to create alias for existing subscription Id.
    :vartype subscription_id: str
    :ivar reseller_id: Reseller Id.
    :vartype reseller_id: str
    :ivar additional_properties: Put alias request additional properties.
    :vartype additional_properties:
     ~azure.mgmt.subscription.models.PutAliasRequestAdditionalProperties
    """

    _attribute_map = {
        "display_name": {"key": "displayName", "type": "str"},
        "workload": {"key": "workload", "type": "str"},
        "billing_scope": {"key": "billingScope", "type": "str"},
        "subscription_id": {"key": "subscriptionId", "type": "str"},
        "reseller_id": {"key": "resellerId", "type": "str"},
        "additional_properties": {"key": "additionalProperties", "type": "PutAliasRequestAdditionalProperties"},
    }

    def __init__(
        self,
        *,
        display_name: Optional[str] = None,
        workload: Optional[Union[str, "_models.Workload"]] = None,
        billing_scope: Optional[str] = None,
        subscription_id: Optional[str] = None,
        reseller_id: Optional[str] = None,
        additional_properties: Optional["_models.PutAliasRequestAdditionalProperties"] = None,
        **kwargs: Any
    ) -> None:
        """
        :keyword display_name: The friendly name of the subscription.
        :paramtype display_name: str
        :keyword workload: The workload type of the subscription. It can be either Production or
         DevTest. Known values are: "Production" and "DevTest".
        :paramtype workload: str or ~azure.mgmt.subscription.models.Workload
        :keyword billing_scope: Billing scope of the subscription.
         For CustomerLed and FieldLed -
         /billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/invoiceSections/{invoiceSectionName}
         For PartnerLed - /billingAccounts/{billingAccountName}/customers/{customerName}
         For Legacy EA -
         /billingAccounts/{billingAccountName}/enrollmentAccounts/{enrollmentAccountName}.
        :paramtype billing_scope: str
        :keyword subscription_id: This parameter can be used to create alias for existing subscription
         Id.
        :paramtype subscription_id: str
        :keyword reseller_id: Reseller Id.
        :paramtype reseller_id: str
        :keyword additional_properties: Put alias request additional properties.
        :paramtype additional_properties:
         ~azure.mgmt.subscription.models.PutAliasRequestAdditionalProperties
        """
        super().__init__(**kwargs)
        self.display_name = display_name
        self.workload = workload
        self.billing_scope = billing_scope
        self.subscription_id = subscription_id
        self.reseller_id = reseller_id
        self.additional_properties = additional_properties


class PutTenantPolicyRequestProperties(_serialization.Model):
    """Put tenant policy request properties.

    :ivar block_subscriptions_leaving_tenant: Blocks the leaving of subscriptions from user's
     tenant.
    :vartype block_subscriptions_leaving_tenant: bool
    :ivar block_subscriptions_into_tenant: Blocks the entering of subscriptions into user's tenant.
    :vartype block_subscriptions_into_tenant: bool
    :ivar exempted_principals: List of user objectIds that are exempted from the set subscription
     tenant policies for the user's tenant.
    :vartype exempted_principals: list[str]
    """

    _attribute_map = {
        "block_subscriptions_leaving_tenant": {"key": "blockSubscriptionsLeavingTenant", "type": "bool"},
        "block_subscriptions_into_tenant": {"key": "blockSubscriptionsIntoTenant", "type": "bool"},
        "exempted_principals": {"key": "exemptedPrincipals", "type": "[str]"},
    }

    def __init__(
        self,
        *,
        block_subscriptions_leaving_tenant: Optional[bool] = None,
        block_subscriptions_into_tenant: Optional[bool] = None,
        exempted_principals: Optional[list[str]] = None,
        **kwargs: Any
    ) -> None:
        """
        :keyword block_subscriptions_leaving_tenant: Blocks the leaving of subscriptions from user's
         tenant.
        :paramtype block_subscriptions_leaving_tenant: bool
        :keyword block_subscriptions_into_tenant: Blocks the entering of subscriptions into user's
         tenant.
        :paramtype block_subscriptions_into_tenant: bool
        :keyword exempted_principals: List of user objectIds that are exempted from the set
         subscription tenant policies for the user's tenant.
        :paramtype exempted_principals: list[str]
        """
        super().__init__(**kwargs)
        self.block_subscriptions_leaving_tenant = block_subscriptions_leaving_tenant
        self.block_subscriptions_into_tenant = block_subscriptions_into_tenant
        self.exempted_principals = exempted_principals


class RenamedSubscriptionId(_serialization.Model):
    """The ID of the subscriptions that is being renamed.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar subscription_id: The ID of the subscriptions that is being renamed.
    :vartype subscription_id: str
    """

    _validation = {
        "subscription_id": {"readonly": True},
    }

    _attribute_map = {
        "subscription_id": {"key": "subscriptionId", "type": "str"},
    }

    def __init__(self, **kwargs: Any) -> None:
        """ """
        super().__init__(**kwargs)
        self.subscription_id: Optional[str] = None


class ServiceTenantResponse(_serialization.Model):
    """Billing account service tenant.

    :ivar tenant_id: Service tenant id.
    :vartype tenant_id: str
    :ivar tenant_name: Service tenant name.
    :vartype tenant_name: str
    """

    _attribute_map = {
        "tenant_id": {"key": "tenantId", "type": "str"},
        "tenant_name": {"key": "tenantName", "type": "str"},
    }

    def __init__(self, *, tenant_id: Optional[str] = None, tenant_name: Optional[str] = None, **kwargs: Any) -> None:
        """
        :keyword tenant_id: Service tenant id.
        :paramtype tenant_id: str
        :keyword tenant_name: Service tenant name.
        :paramtype tenant_name: str
        """
        super().__init__(**kwargs)
        self.tenant_id = tenant_id
        self.tenant_name = tenant_name


class SubscriptionAliasListResult(_serialization.Model):
    """The list of aliases.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar value: The list of subscription aliases.
    :vartype value: list[~azure.mgmt.subscription.models.SubscriptionAliasResponse]
    :ivar next_link: The link (url) to the next page of results.
    :vartype next_link: str
    """

    _validation = {
        "value": {"readonly": True},
        "next_link": {"readonly": True},
    }

    _attribute_map = {
        "value": {"key": "value", "type": "[SubscriptionAliasResponse]"},
        "next_link": {"key": "nextLink", "type": "str"},
    }

    def __init__(self, **kwargs: Any) -> None:
        """ """
        super().__init__(**kwargs)
        self.value: Optional[list["_models.SubscriptionAliasResponse"]] = None
        self.next_link: Optional[str] = None


class SubscriptionAliasResponse(ProxyResource):
    """Subscription Information with the alias.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar id: Fully qualified resource ID for the resource. E.g.
     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}".
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or
     "Microsoft.Storage/storageAccounts".
    :vartype type: str
    :ivar system_data: Azure Resource Manager metadata containing createdBy and modifiedBy
     information.
    :vartype system_data: ~azure.mgmt.subscription.models.SystemData
    :ivar properties: Subscription Alias response properties.
    :vartype properties: ~azure.mgmt.subscription.models.SubscriptionAliasResponseProperties
    """

    _validation = {
        "id": {"readonly": True},
        "name": {"readonly": True},
        "type": {"readonly": True},
        "system_data": {"readonly": True},
    }

    _attribute_map = {
        "id": {"key": "id", "type": "str"},
        "name": {"key": "name", "type": "str"},
        "type": {"key": "type", "type": "str"},
        "system_data": {"key": "systemData", "type": "SystemData"},
        "properties": {"key": "properties", "type": "SubscriptionAliasResponseProperties"},
    }

    def __init__(
        self, *, properties: Optional["_models.SubscriptionAliasResponseProperties"] = None, **kwargs: Any
    ) -> None:
        """
        :keyword properties: Subscription Alias response properties.
        :paramtype properties: ~azure.mgmt.subscription.models.SubscriptionAliasResponseProperties
        """
        super().__init__(**kwargs)
        self.properties = properties


class SubscriptionAliasResponseProperties(_serialization.Model):
    """Put subscription creation result properties.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar subscription_id: Newly created subscription Id.
    :vartype subscription_id: str
    :ivar display_name: The display name of the subscription.
    :vartype display_name: str
    :ivar provisioning_state: The provisioning state of the resource. Known values are: "Accepted",
     "Succeeded", and "Failed".
    :vartype provisioning_state: str or ~azure.mgmt.subscription.models.ProvisioningState
    :ivar accept_ownership_url: Url to accept ownership of the subscription.
    :vartype accept_ownership_url: str
    :ivar accept_ownership_state: The accept ownership state of the resource. Known values are:
     "Pending", "Completed", and "Expired".
    :vartype accept_ownership_state: str or ~azure.mgmt.subscription.models.AcceptOwnership
    :ivar billing_scope: Billing scope of the subscription.
     For CustomerLed and FieldLed -
     /billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/invoiceSections/{invoiceSectionName}
     For PartnerLed - /billingAccounts/{billingAccountName}/customers/{customerName}
     For Legacy EA -
     /billingAccounts/{billingAccountName}/enrollmentAccounts/{enrollmentAccountName}.
    :vartype billing_scope: str
    :ivar workload: The workload type of the subscription. It can be either Production or DevTest.
     Known values are: "Production" and "DevTest".
    :vartype workload: str or ~azure.mgmt.subscription.models.Workload
    :ivar reseller_id: Reseller Id.
    :vartype reseller_id: str
    :ivar subscription_owner_id: Owner Id of the subscription.
    :vartype subscription_owner_id: str
    :ivar management_group_id: The Management Group Id.
    :vartype management_group_id: str
    :ivar created_time: Created Time.
    :vartype created_time: str
    :ivar tags: Tags for the subscription.
    :vartype tags: dict[str, str]
    """

    _validation = {
        "subscription_id": {"readonly": True},
        "provisioning_state": {"readonly": True},
        "accept_ownership_url": {"readonly": True},
        "accept_ownership_state": {"readonly": True},
    }

    _attribute_map = {
        "subscription_id": {"key": "subscriptionId", "type": "str"},
        "display_name": {"key": "displayName", "type": "str"},
        "provisioning_state": {"key": "provisioningState", "type": "str"},
        "accept_ownership_url": {"key": "acceptOwnershipUrl", "type": "str"},
        "accept_ownership_state": {"key": "acceptOwnershipState", "type": "str"},
        "billing_scope": {"key": "billingScope", "type": "str"},
        "workload": {"key": "workload", "type": "str"},
        "reseller_id": {"key": "resellerId", "type": "str"},
        "subscription_owner_id": {"key": "subscriptionOwnerId", "type": "str"},
        "management_group_id": {"key": "managementGroupId", "type": "str"},
        "created_time": {"key": "createdTime", "type": "str"},
        "tags": {"key": "tags", "type": "{str}"},
    }

    def __init__(
        self,
        *,
        display_name: Optional[str] = None,
        billing_scope: Optional[str] = None,
        workload: Optional[Union[str, "_models.Workload"]] = None,
        reseller_id: Optional[str] = None,
        subscription_owner_id: Optional[str] = None,
        management_group_id: Optional[str] = None,
        created_time: Optional[str] = None,
        tags: Optional[dict[str, str]] = None,
        **kwargs: Any
    ) -> None:
        """
        :keyword display_name: The display name of the subscription.
        :paramtype display_name: str
        :keyword billing_scope: Billing scope of the subscription.
         For CustomerLed and FieldLed -
         /billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/invoiceSections/{invoiceSectionName}
         For PartnerLed - /billingAccounts/{billingAccountName}/customers/{customerName}
         For Legacy EA -
         /billingAccounts/{billingAccountName}/enrollmentAccounts/{enrollmentAccountName}.
        :paramtype billing_scope: str
        :keyword workload: The workload type of the subscription. It can be either Production or
         DevTest. Known values are: "Production" and "DevTest".
        :paramtype workload: str or ~azure.mgmt.subscription.models.Workload
        :keyword reseller_id: Reseller Id.
        :paramtype reseller_id: str
        :keyword subscription_owner_id: Owner Id of the subscription.
        :paramtype subscription_owner_id: str
        :keyword management_group_id: The Management Group Id.
        :paramtype management_group_id: str
        :keyword created_time: Created Time.
        :paramtype created_time: str
        :keyword tags: Tags for the subscription.
        :paramtype tags: dict[str, str]
        """
        super().__init__(**kwargs)
        self.subscription_id: Optional[str] = None
        self.display_name = display_name
        self.provisioning_state: Optional[Union[str, "_models.ProvisioningState"]] = None
        self.accept_ownership_url: Optional[str] = None
        self.accept_ownership_state: Optional[Union[str, "_models.AcceptOwnership"]] = None
        self.billing_scope = billing_scope
        self.workload = workload
        self.reseller_id = reseller_id
        self.subscription_owner_id = subscription_owner_id
        self.management_group_id = management_group_id
        self.created_time = created_time
        self.tags = tags


class SubscriptionCreationResult(_serialization.Model):
    """The created subscription object.

    :ivar subscription_link: The link to the new subscription. Use this link to check the status of
     subscription creation operation.
    :vartype subscription_link: str
    """

    _attribute_map = {
        "subscription_link": {"key": "subscriptionLink", "type": "str"},
    }

    def __init__(self, *, subscription_link: Optional[str] = None, **kwargs: Any) -> None:
        """
        :keyword subscription_link: The link to the new subscription. Use this link to check the status
         of subscription creation operation.
        :paramtype subscription_link: str
        """
        super().__init__(**kwargs)
        self.subscription_link = subscription_link


class SubscriptionName(_serialization.Model):
    """The new name of the subscription.

    :ivar subscription_name: New subscription name.
    :vartype subscription_name: str
    """

    _attribute_map = {
        "subscription_name": {"key": "subscriptionName", "type": "str"},
    }

    def __init__(self, *, subscription_name: Optional[str] = None, **kwargs: Any) -> None:
        """
        :keyword subscription_name: New subscription name.
        :paramtype subscription_name: str
        """
        super().__init__(**kwargs)
        self.subscription_name = subscription_name


class SystemData(_serialization.Model):
    """Metadata pertaining to creation and last modification of the resource.

    :ivar created_by: The identity that created the resource.
    :vartype created_by: str
    :ivar created_by_type: The type of identity that created the resource. Known values are:
     "User", "Application", "ManagedIdentity", and "Key".
    :vartype created_by_type: str or ~azure.mgmt.subscription.models.CreatedByType
    :ivar created_at: The timestamp of resource creation (UTC).
    :vartype created_at: ~datetime.datetime
    :ivar last_modified_by: The identity that last modified the resource.
    :vartype last_modified_by: str
    :ivar last_modified_by_type: The type of identity that last modified the resource. Known values
     are: "User", "Application", "ManagedIdentity", and "Key".
    :vartype last_modified_by_type: str or ~azure.mgmt.subscription.models.CreatedByType
    :ivar last_modified_at: The timestamp of resource last modification (UTC).
    :vartype last_modified_at: ~datetime.datetime
    """

    _attribute_map = {
        "created_by": {"key": "createdBy", "type": "str"},
        "created_by_type": {"key": "createdByType", "type": "str"},
        "created_at": {"key": "createdAt", "type": "iso-8601"},
        "last_modified_by": {"key": "lastModifiedBy", "type": "str"},
        "last_modified_by_type": {"key": "lastModifiedByType", "type": "str"},
        "last_modified_at": {"key": "lastModifiedAt", "type": "iso-8601"},
    }

    def __init__(
        self,
        *,
        created_by: Optional[str] = None,
        created_by_type: Optional[Union[str, "_models.CreatedByType"]] = None,
        created_at: Optional[datetime.datetime] = None,
        last_modified_by: Optional[str] = None,
        last_modified_by_type: Optional[Union[str, "_models.CreatedByType"]] = None,
        last_modified_at: Optional[datetime.datetime] = None,
        **kwargs: Any
    ) -> None:
        """
        :keyword created_by: The identity that created the resource.
        :paramtype created_by: str
        :keyword created_by_type: The type of identity that created the resource. Known values are:
         "User", "Application", "ManagedIdentity", and "Key".
        :paramtype created_by_type: str or ~azure.mgmt.subscription.models.CreatedByType
        :keyword created_at: The timestamp of resource creation (UTC).
        :paramtype created_at: ~datetime.datetime
        :keyword last_modified_by: The identity that last modified the resource.
        :paramtype last_modified_by: str
        :keyword last_modified_by_type: The type of identity that last modified the resource. Known
         values are: "User", "Application", "ManagedIdentity", and "Key".
        :paramtype last_modified_by_type: str or ~azure.mgmt.subscription.models.CreatedByType
        :keyword last_modified_at: The timestamp of resource last modification (UTC).
        :paramtype last_modified_at: ~datetime.datetime
        """
        super().__init__(**kwargs)
        self.created_by = created_by
        self.created_by_type = created_by_type
        self.created_at = created_at
        self.last_modified_by = last_modified_by
        self.last_modified_by_type = last_modified_by_type
        self.last_modified_at = last_modified_at


class TargetDirectoryListResult(_serialization.Model):
    """Subscription Response to list out Changed Target Directory.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar value: The list of subscription response to changed target directory.
    :vartype value: list[~azure.mgmt.subscription.models.TargetDirectoryResult]
    :ivar next_link: The link (url) to the next page of results.
    :vartype next_link: str
    """

    _validation = {
        "value": {"readonly": True},
        "next_link": {"readonly": True},
    }

    _attribute_map = {
        "value": {"key": "value", "type": "[TargetDirectoryResult]"},
        "next_link": {"key": "nextLink", "type": "str"},
    }

    def __init__(self, **kwargs: Any) -> None:
        """ """
        super().__init__(**kwargs)
        self.value: Optional[list["_models.TargetDirectoryResult"]] = None
        self.next_link: Optional[str] = None


class TargetDirectoryRequest(_serialization.Model):
    """Subscription Request for Changed Target Directory.

    :ivar properties: Target Directory request properties.
    :vartype properties: ~azure.mgmt.subscription.models.TargetDirectoryRequestProperties
    """

    _attribute_map = {
        "properties": {"key": "properties", "type": "TargetDirectoryRequestProperties"},
    }

    def __init__(
        self, *, properties: Optional["_models.TargetDirectoryRequestProperties"] = None, **kwargs: Any
    ) -> None:
        """
        :keyword properties: Target Directory request properties.
        :paramtype properties: ~azure.mgmt.subscription.models.TargetDirectoryRequestProperties
        """
        super().__init__(**kwargs)
        self.properties = properties


class TargetDirectoryRequestProperties(_serialization.Model):
    """Properties of subscription Request for Changed Target Directory.

    :ivar destination_owner_id: The destination OwnerId, can be object id or email address.
    :vartype destination_owner_id: str
    :ivar destination_tenant_id: The destination Tenant id where subscription needs to be accepted.
    :vartype destination_tenant_id: str
    """

    _attribute_map = {
        "destination_owner_id": {"key": "destinationOwnerId", "type": "str"},
        "destination_tenant_id": {"key": "destinationTenantId", "type": "str"},
    }

    def __init__(
        self, *, destination_owner_id: Optional[str] = None, destination_tenant_id: Optional[str] = None, **kwargs: Any
    ) -> None:
        """
        :keyword destination_owner_id: The destination OwnerId, can be object id or email address.
        :paramtype destination_owner_id: str
        :keyword destination_tenant_id: The destination Tenant id where subscription needs to be
         accepted.
        :paramtype destination_tenant_id: str
        """
        super().__init__(**kwargs)
        self.destination_owner_id = destination_owner_id
        self.destination_tenant_id = destination_tenant_id


class TargetDirectoryResult(ProxyResource):
    """Subscription Response for Changed Target Directory.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar id: Fully qualified resource ID for the resource. E.g.
     "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}".
    :vartype id: str
    :ivar name: The name of the resource.
    :vartype name: str
    :ivar type: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or
     "Microsoft.Storage/storageAccounts".
    :vartype type: str
    :ivar system_data: Azure Resource Manager metadata containing createdBy and modifiedBy
     information.
    :vartype system_data: ~azure.mgmt.subscription.models.SystemData
    :ivar properties: Subscription Changed Target Directory response properties.
    :vartype properties: ~azure.mgmt.subscription.models.TargetDirectoryResultProperties
    """

    _validation = {
        "id": {"readonly": True},
        "name": {"readonly": True},
        "type": {"readonly": True},
        "system_data": {"readonly": True},
    }

    _attribute_map = {
        "id": {"key": "id", "type": "str"},
        "name": {"key": "name", "type": "str"},
        "type": {"key": "type", "type": "str"},
        "system_data": {"key": "systemData", "type": "SystemData"},
        "properties": {"key": "properties", "type": "TargetDirectoryResultProperties"},
    }

    def __init__(
        self, *, properties: Optional["_models.TargetDirectoryResultProperties"] = None, **kwargs: Any
    ) -> None:
        """
        :keyword properties: Subscription Changed Target Directory response properties.
        :paramtype properties: ~azure.mgmt.subscription.models.TargetDirectoryResultProperties
        """
        super().__init__(**kwargs)
        self.properties = properties


class TargetDirectoryResultProperties(_serialization.Model):
    """Properties of subscription Response for Changed Target Directory.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar destination_tenant_id: Destination Tenant Id where Subscription will be accepted.
    :vartype destination_tenant_id: str
    :ivar destination_owner_id: Destination Owner Id where Subscription will be accepted.
    :vartype destination_owner_id: str
    :ivar subscription_id: The id of the subscription being transferred.
    :vartype subscription_id: str
    :ivar created_date: The UTC date and time when the transfer request was created.
    :vartype created_date: ~datetime.datetime
    :ivar accepted_date: The UTC date and time when the transfer request was accepted.
    :vartype accepted_date: ~datetime.datetime
    :ivar source_owner_email: The email address of the user who initiated the transfer request. If
     the request was generated by a Service Principal, this field may be null.
    :vartype source_owner_email: str
    :ivar source_owner_id: The object id of the user who initiated the transfer request.
    :vartype source_owner_id: str
    :ivar source_tenant_id: The id of the tenant where the subscription originally resided.
    :vartype source_tenant_id: str
    :ivar status: Status of the subscription transfer operation. Known values are: "Initialized",
     "InProgress", and "Completed".
    :vartype status: str or ~azure.mgmt.subscription.models.ChangeDirectoryOperationStatus
    :ivar expires_on: Subscription Initiate Request Expiry time.
    :vartype expires_on: ~datetime.datetime
    """

    _validation = {
        "destination_tenant_id": {
            "readonly": True,
            "pattern": r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
        },
        "destination_owner_id": {
            "readonly": True,
            "pattern": r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
        },
        "subscription_id": {
            "readonly": True,
            "pattern": r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
        },
        "created_date": {"readonly": True},
        "accepted_date": {"readonly": True},
        "source_owner_email": {"readonly": True},
        "source_owner_id": {
            "readonly": True,
            "pattern": r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
        },
        "source_tenant_id": {
            "readonly": True,
            "pattern": r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
        },
        "status": {"readonly": True},
        "expires_on": {"readonly": True},
    }

    _attribute_map = {
        "destination_tenant_id": {"key": "destinationTenantId", "type": "str"},
        "destination_owner_id": {"key": "destinationOwnerId", "type": "str"},
        "subscription_id": {"key": "subscriptionId", "type": "str"},
        "created_date": {"key": "createdDate", "type": "iso-8601"},
        "accepted_date": {"key": "acceptedDate", "type": "iso-8601"},
        "source_owner_email": {"key": "sourceOwnerEmail", "type": "str"},
        "source_owner_id": {"key": "sourceOwnerId", "type": "str"},
        "source_tenant_id": {"key": "sourceTenantId", "type": "str"},
        "status": {"key": "status", "type": "str"},
        "expires_on": {"key": "expiresOn", "type": "iso-8601"},
    }

    def __init__(self, **kwargs: Any) -> None:
        """ """
        super().__init__(**kwargs)
        self.destination_tenant_id: Optional[str] = None
        self.destination_owner_id: Optional[str] = None
        self.subscription_id: Optional[str] = None
        self.created_date: Optional[datetime.datetime] = None
        self.accepted_date: Optional[datetime.datetime] = None
        self.source_owner_email: Optional[str] = None
        self.source_owner_id: Optional[str] = None
        self.source_tenant_id: Optional[str] = None
        self.status: Optional[Union[str, "_models.ChangeDirectoryOperationStatus"]] = None
        self.expires_on: Optional[datetime.datetime] = None


class TenantPolicy(_serialization.Model):
    """Tenant policy.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar policy_id: Policy Id.
    :vartype policy_id: str
    :ivar block_subscriptions_leaving_tenant: Blocks the leaving of subscriptions from user's
     tenant.
    :vartype block_subscriptions_leaving_tenant: bool
    :ivar block_subscriptions_into_tenant: Blocks the entering of subscriptions into user's tenant.
    :vartype block_subscriptions_into_tenant: bool
    :ivar exempted_principals: List of user objectIds that are exempted from the set subscription
     tenant policies for the user's tenant.
    :vartype exempted_principals: list[str]
    """

    _validation = {
        "policy_id": {"readonly": True},
    }

    _attribute_map = {
        "policy_id": {"key": "policyId", "type": "str"},
        "block_subscriptions_leaving_tenant": {"key": "blockSubscriptionsLeavingTenant", "type": "bool"},
        "block_subscriptions_into_tenant": {"key": "blockSubscriptionsIntoTenant", "type": "bool"},
        "exempted_principals": {"key": "exemptedPrincipals", "type": "[str]"},
    }

    def __init__(
        self,
        *,
        block_subscriptions_leaving_tenant: Optional[bool] = None,
        block_subscriptions_into_tenant: Optional[bool] = None,
        exempted_principals: Optional[list[str]] = None,
        **kwargs: Any
    ) -> None:
        """
        :keyword block_subscriptions_leaving_tenant: Blocks the leaving of subscriptions from user's
         tenant.
        :paramtype block_subscriptions_leaving_tenant: bool
        :keyword block_subscriptions_into_tenant: Blocks the entering of subscriptions into user's
         tenant.
        :paramtype block_subscriptions_into_tenant: bool
        :keyword exempted_principals: List of user objectIds that are exempted from the set
         subscription tenant policies for the user's tenant.
        :paramtype exempted_principals: list[str]
        """
        super().__init__(**kwargs)
        self.policy_id: Optional[str] = None
        self.block_subscriptions_leaving_tenant = block_subscriptions_leaving_tenant
        self.block_subscriptions_into_tenant = block_subscriptions_into_tenant
        self.exempted_principals = exempted_principals
