# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class AcceptOwnership(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The accept ownership state of the resource."""

    PENDING = "Pending"
    """Pending"""
    COMPLETED = "Completed"
    """Completed"""
    EXPIRED = "Expired"
    """Expired"""


class ActionType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Enum. Indicates the action type. "Internal" refers to actions that are for internal only APIs."""

    INTERNAL = "Internal"


class ChangeDirectoryOperationStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Status of the subscription transfer operation."""

    INITIALIZED = "Initialized"
    """The subscription transfer request has been created and is waiting for acceptance by the
    destination tenant."""
    IN_PROGRESS = "InProgress"
    """The subscription transfer request has been accepted by the destination tenant and the transfer
    is in progress."""
    COMPLETED = "Completed"
    """The subscription transfer has been completed and is now owned by the destination tenant."""


class CreatedByType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The type of identity that created the resource."""

    USER = "User"
    APPLICATION = "Application"
    MANAGED_IDENTITY = "ManagedIdentity"
    KEY = "Key"


class Origin(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The intended executor of the operation; as in Resource Based Access Control (RBAC) and audit
    logs UX. Default value is "user,system".
    """

    USER = "user"
    SYSTEM = "system"
    USER_SYSTEM = "user,system"


class Provisioning(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The provisioning state of the resource."""

    PENDING = "Pending"
    """Pending"""
    ACCEPTED = "Accepted"
    """Accepted"""
    SUCCEEDED = "Succeeded"
    """Succeeded"""


class ProvisioningState(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The provisioning state of the resource."""

    ACCEPTED = "Accepted"
    """Accepted"""
    SUCCEEDED = "Succeeded"
    """Succeeded"""
    FAILED = "Failed"
    """Failed"""


class Workload(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The workload type of the subscription. It can be either Production or DevTest."""

    PRODUCTION = "Production"
    """Production"""
    DEV_TEST = "DevTest"
    """DevTest"""
